### ISSUE TITLE
can not open git graph in v1.57

### ISSUE THREAD

**Issue by Karing2016** [mhutchie/vscode-git-graph#525] opened 2021-06-13 14:37 UTC
Issue Type: <b>Bug</b>

1. press "view git graph" button
2. git graph tab shows:
Repo:
Branches:
Show Remote Branches

Extension version: 1.30.0
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No
Remote OS version: Linux x64 3.10.107-1-tlinux2_kvm_guest-0050

**Comment by mhutchie** [comment] 2021-06-14 00:34
Duplicate of #436.

Please see [my previous comment](https://github.com/mhutchie/vscode-git-graph/issues/436#issuecomment-744678297) for an explanation of what's occurring, and the resolution / actions you can take. While you can easily resolve this issue yourself if it is cause 1, I suspect you likely have cause 2 (as there are still issues with the Visual Studio Code Webview implementation, even though the vscode bug I previously mentioned has since been closed).

**Closed as completed by mhutchie** 2021-06-14 00:34 UTC
Labels: vscode-bug
