### ISSUE TITLE
Refresh built-in SCM panel / other Git UI automatically

### ISSUE THREAD

**Issue by borekb** [mhutchie/vscode-git-graph#500] opened 2021-04-15 10:49 UTC
Sometimes, Git actions done via Git Graph are only reflected by the built-in Git support (e.g., the SCM sidebar / panel) after I manually click _Refresh_ there. It doesn't always happen but it's something I'm encountering encountered regularly during my day-to-day work so I thought I'd report it here.

Not sure if this extensions can do anything about it, maybe it calls all the relevant APIs already (if there are any, I don't really know!).

**Comment by mhutchie** [comment] 2021-04-15 11:10
Hi @borekb,

This is a duplicate of #275, #280, #282 & #472.

Please see [this previous comment of mine](https://github.com/mhutchie/vscode-git-graph/issues/282#issuecomment-602097824), which explains the cause of the behaviour you're observing (a known Visual Studio Code issue).

**Closed as completed by mhutchie** 2021-04-15 11:10 UTC
Labels: vscode-bug

**Comment by borekb** [comment] 2021-04-15 11:53
🤦‍♂️ and I promise I searched the issues! Sorry & thanks for the reply.
