### ISSUE TITLE
Offer another chance to name branch if name already exists

### ISSUE THREAD

**Issue by MetRonnie** [mhutchie/vscode-git-graph#464] opened 2021-02-16 15:58 UTC
**Describe the improvement that you'd like**
When creating a new branch, if you accidentally try to give the branch a name of a pre-existing branch, you get an error dialog "Error: Unable to Create Branch". The only option is to press the "Dismiss" button, forcing you to right-click the commit again and type out a branch name again.

It would be nice if the textbox for naming the branch came back, pre-populated with what you typed so you can try a different name.

**Comment by mhutchie** [comment] 2021-02-16 21:58
Hi @MetRonnie,

This is a duplicate of #390, and is already implemented and available in the latest extension beta release, and will be available soon in Git Graph 1.29.0.

If you'd like to use it before the next release, you can download [v1.29.0-beta.5](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.29.0-beta.5), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Closed by mhutchie** 2021-02-16 21:58 UTC
Labels: improvement

**Comment by MetRonnie** [comment] 2021-02-16 22:01
Ah nice! Missed that when searching for existing issues
