### ISSUE TITLE
Visualize `git reflog`

### ISSUE THREAD

**Issue by fsteinmetz** [mhutchie/vscode-git-graph#302] opened 2020-05-06 06:30 UTC
It would be nice to have an option to visualize the content of `git reflog` to recover commits, for example to undo a rebase.
smartgit does this with a checkbox to display "recyclable commits". The graph view is very useful in this context, compared to the linear view of `git reflog`.

**Comment by mhutchie** [comment] 2020-05-06 21:46
Hi @fsteinmetz,

This is a duplicate of #89, which has recently been implemented and will be available in the next release (Git Graph 1.23.0).

If you'd like to use it before the next release, you can download [v1.23.0-beta.4](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.23.0-beta.4), and install it following the "Manual Installation" instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Closed by mhutchie** 2020-05-06 21:46 UTC
Labels: feature request

**Comment by fsteinmetz** [comment] 2020-05-07 08:05
Oh I missed it, sorry.
I'm glad to learn that it is already implemented. Thumbs up !
