### ISSUE TITLE
[Allow to] move Git Graph to Side|Activity bar and/or panel

### ISSUE THREAD

**Issue by JonatasAmaral** [mhutchie/vscode-git-graph#572] opened 2021-09-30 02:01 UTC
Move, or even better, allow the user to move the GitGraph editor to (and out from) the sidebar, and why not, the bottom panel, like some editors can do, those created by extensions included (ex: GitLens, Todo Tree)

The best example of this behavior is the (v1.59+) built-in terminal, that can be moved across sidebar, activity bar, bottom panel **and** (in a different way) to the editor area too.

It would be really nice for when side-by-side with files, but easily toggle it "on/off"

**Comment by mhutchie** [comment] 2021-10-07 11:19
Duplicate of #438. Please read [my previous response](https://github.com/mhutchie/vscode-git-graph/issues/438#issuecomment-745803679) for more information.

**Closed as completed by mhutchie** 2021-10-07 11:19 UTC
Labels: duplicate
