### ISSUE TITLE
Allow drag&drop to move local and remote branches

### ISSUE THREAD

**Issue by rhaschke** [mhutchie/vscode-git-graph#560] opened 2021-09-03 11:19 UTC
It would be great if branches could be moved (forwarded, reset, pushed to remotes) by simple drag-and-drop of the branch labels. I'm used to this feature from [`qgit`](https://github.com/tibirna/qgit). Would be great if `git-graph` could provide that as well.

**Comment by mhutchie** [comment] 2021-09-03 11:29
Hi @rhaschke,

Thank you for raising this feature request! I'll close it as it's a duplicate of #19.

**Closed as completed by mhutchie** 2021-09-03 11:29 UTC
Labels: duplicate
