### ISSUE TITLE
Doesn't work with Multiple Repositories 

### ISSUE THREAD

**Issue by timothymarois** [mhutchie/vscode-git-graph#16] opened 2019-02-27 20:06 UTC
**Describe the bug**
Right now it's only selecting the first repo in the list regardless of the one we've selected.
If you have multiple repos, it doesn't load them, and there is no way to load them in the graph

**What does the bug relate to**
Repo showed in the graph

**To reproduce**
Click git graph, and then try to change repos, git graph only reflects the first repo in list

**Expected behaviour**
Should change between repos if we've selected another 

**Environment**
 - OS: MacOS

**Comment by mhutchie** [comment] 2019-02-27 20:21
Is this referring to when there are multiple root folders in the Visual Studio Code workspace, where each folder could contain its own Git repository?

**Comment by timothymarois** [comment] 2019-02-27 20:22
@mhutchie I believe that is correct. I have one workspace and have added multiple directories to it which all have their own repos.

**Comment by mhutchie** [comment] 2019-02-27 20:40
This is a duplicate of #13, just using different terminology.

I’m definitely adding support for this functionality soon. v1.4.0 is going to be released in the next two days which has a quite distint set of new features, this will be available in the next release after v1.4.0. It will focus on changes in the top control bar, which is where you’ll then be able to select the desired git repository when multiple are present in the VSCode workspace.

**Closed** 2019-02-27 22:11 UTC
Labels: bug

**Comment by mhutchie** [comment] 2019-03-09 09:27
This is now completed and is available in 1.4.1, which was just release.
