### ISSUE TITLE
Gitgraph not working on VSCode Insiders (v1.46) while using Remote SSH

### ISSUE THREAD

**Issue by mfmayer** [mhutchie/vscode-git-graph#314] opened 2020-05-29 06:39 UTC
**Describe the Bug**
While using VSCode remote development (at least via SSH) gitgraph is not function in recent VSCode Insider versions. When opening gitgraph it looks like this:
![image](https://user-images.githubusercontent.com/8875306/83228803-2e707400-a187-11ea-8666-4d20b5e4978e.png). 

Gitgraph is working fine while using remote developing with non-insider VSCode (v1.45.1) as well as using it in VSCode Insider locally, while not beeing connected to VSCode remote server.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Install/Update to recent VSCode Insider version
2. Install remote development extensions from Microsoft (e.g. "Remote - SSH")
3. Connect to remote machine where VSCode Server is running
4. Install gitgraph on remote VSCode
5. Try to open gitgraph

**Expected Behaviour**
Gitgraph should work in VSCode Insider while developing remotely via Microsoft remote development extensions.

**Environment**
 - Git Graph Extension Version: 1.23.0
 - Visual Studio Code: 
Version: 1.46.0-insider (system setup)
Commit: 9e439b13d5784538333bee044ca1d1a992bc1c90
Date: 2020-05-28T18:44:47.151Z
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
 - Operating System: 
Windows 10 (client)
Linux (host)

**Comment by mhutchie** [comment] 2020-05-29 08:30
Hi @mfmayer, I understand your frustration.

I've been made aware of this issue occurring occasionally / randomly for a few users across a variety of Visual Studio Code environments and operating systems. In the few reported cases, closing and re-opening the Git Graph View has seemed to resolve the issue for the user.

This was introduced as a bug in a recent version of Visual Studio Code, and is currently being resolved by Microsoft.

I'm closing this issue as the bug is caused by Visual Studio Code itself, is already in the process of being fixed by Microsoft, and there isn't anything I can do in Git Graph to fix this issue in the mean-time until it is fixed by Microsoft.

**Closed by mhutchie** 2020-05-29 08:30 UTC

**Comment by mfmayer** [comment] 2020-05-29 09:31
Thanks for the answer 👍. By the way, I'm not frustrated about your extension. Just the opposite, it's one of my favorite!

Do you have a link to according ticket in VSCode project?

> Hi @mfmayer, I understand your frustration.
> 
> I've been made aware of this issue occurring occasionally / randomly for a few users across a variety of Visual Studio Code environments and operating systems. In the few reported cases, closing and re-opening the Git Graph View has seemed to resolve the issue for the user.
> 
> This was introduced as a bug in a recent version of Visual Studio Code, and is currently being resolved by Microsoft.
> 
> I'm closing this issue as the bug is caused by Visual Studio Code itself, is already in the process of being fixed by Microsoft, and there isn't anything I can do in Git Graph to fix this issue in the mean-time until it is fixed by Microsoft.

**Comment by mhutchie** [comment] 2020-05-29 09:48
Hi @mfmayer, I remember finding the vscode ticket a few months back when I first got reports of it from some users. I can't find the link at the moment because I copied it so long ago, I'll try and dig it up this weekend for you.

**Comment by keisto** [comment] 2020-06-23 21:48
@mhutchie I'm not sure if these extensions broke it, but I recently installed these today and now my Git Graph looks like the photo above:
- https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui
- https://marketplace.visualstudio.com/items?itemName=iocave.monkey-patch

**Comment by mhutchie** [comment] 2020-06-24 07:58
Hi @keisto,

No extensions should impact any others, Microsoft does a great job at isolating them.

Microsoft had fixed this issue for several weeks, but it was unfortunately broken again recently - hopefully they fix it again soon.

**Comment by mhutchie** [comment] 2020-06-24 08:25
Please follow #317 for the tracking of this issue being resolved by Microsoft, it is affecting all extensions that use a [Webview](https://code.visualstudio.com/api/extension-guides/webview).

**Comment by bobmorane06** [comment] 2020-06-24 17:46
I faced the same problem and switched to VSCodium. I had to modify the .json config file to point it to the Microsoft Extensions marketplace to install git graph - see mhutchie's comment in https://github.com/mhutchie/vscode-git-graph/issues/325

**Comment by aurexav** [comment] 2020-08-24 11:36
Again.

```
The folder "xxx" is not within the opened Visual Studio Code workspace, and therefore could not be added to Git Graph.
```

**Comment by lishujun5** [comment] 2021-07-21 03:06
it occurs again recently!!!How can I do?

**Comment by mhutchie** [comment] 2021-07-21 03:26
Hi @lishujun5,

Please check to see if you face the same error as any of the four open Visual Studio Code bugs that are currently affecting all extensions that use Visual Studio Code Webview's (https://github.com/mhutchie/vscode-git-graph/issues?q=is%3Aissue+is%3Aopen+label%3Avscode-bug+). Microsoft is aware of them, and is already working to fix them. If not, please provide more details of what you're experiencing.

**Comment by lishujun5** [comment] 2021-07-21 03:34
Hi @mhutchie,
Thank for your answer, the bugs you said above maybe the same as I meet.Really appreciate

**Comment by Alex44lel** [comment] 2023-02-12 14:09
In my case, I had to GitHub users and that was confusing the extension. I have created a post where I explain how to solve it.

https://stackoverflow.com/questions/75427541/git-graph-not-displaying-information/75427542#75427542
