### ISSUE TITLE
Fetch and Prune tags gives error "would clobber existing tag"

### ISSUE THREAD

**Issue by urielzen** [mhutchie/vscode-git-graph#632] opened 2022-03-04 06:48 UTC
**Describe the Bug**
Getting this error "would clobber existing tag" when clicking the Fetch (and Prune) button in the View Control Bar:
![image](https://user-images.githubusercontent.com/7947179/156712305-4da6eeb7-285e-4a68-8aff-b3931d647cbf.png)

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Enable these 2 settings: `Git-graph › Repository: Fetch And Prune` and `Git-graph › Repository: Fetch And Prune Tags`
2. Add a tag with name "PROD" to your local and push to remote to commit A.
3. remote "PROD" tag is deleted by other user in remote and re-added "PROD" tag in remote to a commit B.
4. Click "Fetch and Prune"

**Expected Behaviour**
I would expect that my initial local "PROD" tag in commit A to be deleted (or "moved") and show instead in commit B, to reflect the change that the other user did in remote.

I can easily fix the issue with the following command but I would like git Graph if possible to help me skip this step
`git fetch --tags -f`

**Environment**
 - Git Graph Extension Version: v1.30.0
 - Operating System: Windows 11

**Comment by mhutchie** [comment] 2022-03-04 07:37
Hi @urielzen,

This is definitely not a bug with Git Graph, as the extension is running the usual Git command as expected, and Git is producing an error message due to the state of your repository. When Git throws an error, the best the extension can do is display the error, so the user can take an appropriate action to resolve it.

The behaviour you’re expecting is not Git’s behaviour, which is not something that anyone can change.

Sometimes repositories can get into states that can’t be resolved with the usual Git commands, and require the use of an additional argument / alternative command. When running a Git command in Git Graph which has a form / confirmation dialog, I’d typically just add an additional option to it enough users would use it (e.g. “Force”). However this is not possible given the nature of this specific command.

As no other users have ever reported this scenario under these repository conditions, I’m inclined to believe this is extremely uncommon, and therefore a manual Git command is a suitable resolution. If other users report similar scenarios in the future, I’ll re-prioritise it accordingly, and re-open / implement it if necessary.

**Closed as completed by mhutchie** 2022-03-04 07:37 UTC
Labels: feature request, nice to have, backlog
