### ISSUE TITLE
Keep controls pinned to the window when scrolling

### ISSUE THREAD

**Issue by ahernsean** [mhutchie/vscode-git-graph#549] opened 2021-08-11 15:29 UTC
**Describe the feature that you'd like**
Currently, when the graph is scrolled, the controls at the top (chosen branches, search, reload, etc.) scroll out of view immediately. This request is for the controls at the top to remain "pinned" to the top of the window, allowing them to still be accessible even when looking at commits far back in history. Screenshot attached of the current controls area above the top of the history tree.
![image](https://user-images.githubusercontent.com/1649300/129058044-915ab610-c433-4fc4-a809-fce1e3a80415.png)

**Comment by mhutchie** [comment] 2021-08-11 22:40
Closing this feature request, as it is a duplicate of #132.

**Closed as completed by mhutchie** 2021-08-11 22:40 UTC
Labels: feature request, duplicate

**Comment by ahernsean** [comment] 2021-08-12 12:25
> Closing this feature request, as it is a duplicate of #132.

Ah ha, thanks. I didn't see that one.
That other item has a proposed PR, but it was back in October. Any idea if that's going to be reviewed/merged?

**Comment by mhutchie** [comment] 2021-08-12 12:53
Hi @ahernsean,

When the feature request was first raised, I quickly identified that there was actually a surprising amount of complexity to it, that made it hard to justify in comparison to implementing new Git capabilities that offered far more net value to users.

One developer worked on a pull request implementing this feature, and although progress was made, ultimately there were still several fundamental issues that meant it wasn’t in a production-ready state. I’ve already had to spend a significant amount of time reviewing the pull request multiple times identifying bugs, so I’m currently not in a position to invest additional time to fix / complete it (due to other higher priority feature requests). I’m aiming to finish implementing it as soon as I’ve completed the higher priority feature requests.

**Comment by ahernsean** [comment] 2021-08-12 13:43
> I’ve already had to spend a significant amount of time reviewing the pull request multiple times identifying bugs, so I’m currently not in a position to invest additional time to fix / complete it (due to other higher priority feature requests). I’m aiming to finish implementing it as soon as I’ve completed the higher priority feature requests.

Good explanation! I don't mean to be a pest. Thanks for your work!
