### ISSUE TITLE
[Bug] Could not register service workers

### ISSUE THREAD

**Issue by YehudaKremer** [mhutchie/vscode-git-graph#621] opened 2022-02-05 20:51 UTC
Hello

I getting this error when trying to open the graph:
> Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

1. just try to open it

**Environment**
 - Git Graph Extension Version:  v1.30.0
 - Visual Studio Code Version: v1.64.0
 - Operating System: Windows 11

![image](https://user-images.githubusercontent.com/946652/152658573-5dc4650a-2276-42c5-add0-957b5f09e880.png)

**Comment by YehudaKremer** [comment] 2022-02-05 20:58
Update: Now it does work for me, the bug is inconsistent, maybe it only happens on my machine 😵‍💫

**Comment by mhutchie** [comment] 2022-02-05 23:37
Hi @YehudaKremer,

This is a duplicate of #508, #511, #514 & #524 - a handful of users reported this when using recent versions of Visual Studio Code. It's a Visual Studio Code bug that Microsoft still hasn't been able to resolve - it affects all extensions that use Visual Studio Code Webview's (not just Git Graph).

**Closed as completed by mhutchie** 2022-02-05 23:37 UTC
Labels: vscode-bug, duplicate

**Comment by YehudaKremer** [comment] 2022-02-05 23:45
i see, thanks for your answer  👍
