### ISSUE TITLE
Can't paste into VS Code search when Git Graph tab is active

### ISSUE THREAD

**Issue by dlech** [mhutchie/vscode-git-graph#528] opened 2021-06-18 20:44 UTC
**Describe the Bug**
When the *Git Graph* tab is open, <kbd>Ctrl</kbd>+<kbd>V</kbd> no longer works when trying to paste in the VS Code search box.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Open a git repository
2. Copy some text to the clipboard
3. Paste it in the search box - works OK
4. Clear the search box
5. Open the *Git Graph* page for the repository
6. Try to paste in the search box again - no longer works

**Expected Behaviour**
This extensions shouldn't break VS Code.

**Environment**
 - Git Graph Extension Version:  1.30.0
 - Visual Studio Code Version: 1.57.1
 - Operating System: Ubuntu 20.04

**Comment by mhutchie** [comment] 2021-06-18 22:16
Hi @dlech,

I've been able to replicate this bug, and it's caused by a bug in the Visual Studio Code [Webview](https://code.visualstudio.com/api/extension-guides/webview) implementation that must have been introduced in one of the latest Visual Studio Code releases. Whenever any extension-contributed Webview is visible, the search input can't be pasted into. The Git Graph View uses a Visual Studio Code Webview to be rendered in Visual Studio Code. I've also been able to replicate this exact same bug with numerous other extensions when their Webview's are also visible (i.e. it's not specific to Git Graph, and is a Visual Studio Code bug that affects all extensions that use Webviews).

**Comment by dlech** [comment] 2021-06-18 22:22
Thanks for testing. This could be the bug: https://github.com/microsoft/vscode/issues/116897

**Comment by mhutchie** [comment] 2021-06-18 22:33
I've just raised a new bug in the Visual Studio Code repository for this, as I believe it was only introduced more recently. https://github.com/microsoft/vscode/issues/126716

I'll re-open this Visual Studio Code bug until Microsoft resolves it, as otherwise I'll get duplicates raised by other Git Graph users.

**Comment by dlech** [comment] 2021-06-18 22:36
You are awesome!

**Comment by mhutchie** [comment] 2021-06-18 22:48
Apologies for the inconvenience, hopefully Microsoft will fix it soon.

FYI: From what I'm aware of, they've been making some pretty significant changes to the Visual Studio Code Webview implementation recently. Unfortunately this has caused numerous Webview bugs, that affect all extensions that use Visual Studio Code Webview's. This has a significant impact on Git Graph, as a Webview is used for the core user interface of the extension.

**Comment by mhutchie** [comment] 2021-09-19 08:40
From what I can observe, this Visual Studio Code bug has since be fixed by Microsoft. If you continue to face this issue, please raise it again with Microsoft.

**Closed as completed by mhutchie** 2021-09-19 08:40 UTC
Labels: vscode-bug
