### ISSUE TITLE
Unable to approve "new" SSH connection through the UI

### ISSUE THREAD

**Issue by willpower232** [mhutchie/vscode-git-graph#224] opened 2019-12-02 10:09 UTC
**Describe the Bug**
I cleared my `known_hosts` file and now have to manually approve the first time use of each new SSH connection, including git fetches.

Unfortunately this doesn't appear to be handled by the present UI as the fetch from the extension simply spins forever.

FWIW it also seems that VS Code itself also does not handle this particular scenario. I presume that timeouts aren't an option with this command or the prompt to approve the connection is difficult to detect.

Potentially related to #114 

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. `rm ~/.ssh/known_hosts`
2. Click the fetch button within the git graph tab
3. Wait forever

**Expected Behaviour**
At the very least I would have expected the output console to pop up and complain about something.

**Environment**
 - Git Graph Extension Version: 1.19.1
 - Visual Studio Code Version: 1.40.2
 - Operating System: Ubuntu 19.04

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/1619102/69949165-e2e75100-14e8-11ea-807a-0065c136bc9d.png)

![image](https://user-images.githubusercontent.com/1619102/69949176-ebd82280-14e8-11ea-8f59-700033f6b650.png)

![image](https://user-images.githubusercontent.com/1619102/69948971-7cfac980-14e8-11ea-9659-ae9fcb85fe4c.png)

**Comment by mhutchie** [comment] 2019-12-02 11:07
Git Graph integrates with Askpass to automatically prompt the user for credentials to the remote (that was implemented in the issue you referenced).

Unfortunately the SSH authenticity prompt from Git doesn't use Askpass, and like you presumed:
* There isn't a good timeout option. Although I could add a timeout to git commands run from the extension, it wouldn't be able to provide any more useful information than _"The git command took to long to execute"_ (which doesn't tell the user anything). As some git commands are long running, setting a timeout would merely prevent them from completing (like fetching from a large repo) as there is no way to know the cause of the delay. 
* There isn't a way to detect the prompt as the SSH authenticity prompt is not output on the Git commands stdout or stderr channels (which can be monitored).

I'm closing this issue as from my research there doesn't appear to be any way to detect this scenario, and the behaviour is consistent with Visual Studio Code's handling of this scenario. It is also a one-off occurrence at a platform level per remote SSH host, so it's not as if it would frequently come up.

I'll definitely keep a lookout for solutions if they exist, as I agree that the current behaviour is not ideal, there just doesn't appear to be a solution. If anyone reading this in the future is aware of a solution, please reply to this thread as I'd be keen to implement it.

**Closed by mhutchie** 2019-12-02 11:07 UTC
Labels: bug

**Comment by willpower232** [comment] 2019-12-02 11:12
Thanks for your acknowledgement and this great extension
