### ISSUE TITLE
Tree export as an image?

### ISSUE THREAD

**Issue by mexericas** [mhutchie/vscode-git-graph#626] opened 2022-02-15 12:43 UTC
**Describe the feature that you'd like**
It would be nice if there was a way to export the branch graph as an image. There have been projects where the team was really proud of the result, and being able to print a commemorative poster of the commit graph would be a nice touch. I guess this would fall under the "nice to have" tag more than a requirement, since this is only an aesthetic feature.

Thanks in advance for your time

**Comment by mhutchie** [comment] 2022-02-26 02:28
Hi @radeonthe1st,

I'll close this feature request for now as a duplicate of #606, as this request is likely a subset / additional option on the existing request (which offers functional value to users).

Both #606 & this request are lower priority compared to other feature requests, however by combining them together as an "Export" capability makes them collectively more appealing as a new capability (and prioritised somewhat higher).

**Closed as completed by mhutchie** 2022-02-26 02:28 UTC
Labels: feature request, duplicate
