### ISSUE TITLE
Multiple tabs

### ISSUE THREAD

**Issue by themightychris** [mhutchie/vscode-git-graph#431] opened 2020-12-11 22:28 UTC
I would like a palette command for opening a second instance of the git graph tab. In a multi-root workspace this would be useful for being able to look at two repos at the same time in split panels.

Are there any architectural barriers to multiple git graph tab instances? I've had it happen accidentally a few times in the transition from a single-root to multi-root workspace and they seem to co-exist fine.

**Comment by mhutchie** [comment] 2020-12-11 23:46
Hi @themightychris,

Thank you for raising this feature request, this would be a great capability to have in Git Graph!

Any occurrences of multiple instances of the Git Graph View (that you indicate occurred "accidentally a few times in the transition from a single-root to multi-root workspace"), are actually caused by a Visual Studio Code bug that I'm aware of that occurs exactly in this scenario. The extension actively prevents multiple Git Graph View's being open at the same time, but when Visual Studio Code does this workspace switch, Visual Studio Code can "forget" about the existing view that was previously open, allowing a second to be opened. This is definitely not supported in Git Graph, and I know there are some issues (that might not have been obvious when you've seen it in the past).

This request is definitely possible, I've written Git Graph in a way that's compatible with it, however there is still a significant amount of work required to seamlessly support this in a way I'd be comfortable releasing. There are also a variety of side affects that negatively impact the user - not major, but definitely exist to some extent.

Based on prior conversations I've had with many users, and various other available metrics, I know that multi-root workspace users are definitely a small portion of the Git Graph users. Out of this sub-group of users, your the first to raise that seeing two repositories side-by-side would better suit your workflow (rather than switching repositories via the "Repo" dropdown in a single Git Graph View). I'm sure many others would like this (you're just the first to let me know), however I'm also aware that this is still going to be a small percentage of the overall users.

Additionally, one option that's currently available is for you to just use two separate Visual Studio Code windows (instead of a multi-root workspace), one for each repository. You can then view each repository in their respective Visual Studio Code window. This allows the repository to be just an `Alt+Tab` away, and the Git Graph View is larger in each (no split panels required) - making the view far more usable with more information visible. I'm aware this may not be ideal for your workflow, but the option is at least available to you, or anyone else reading this comment in the future.

I'll move this feature request to the backlog (and close it) for now, because based on the best information I have available, it would require a significant amount of work benefitting a small proportion of users, and there is already an option available to you that allows two repositories to be displayed in two Git Graph View's at the same time. All of these reasons mean this feature request would naturally be prioritised lower than many other open feature requests for now. In saying this, I definitely think this would valuable to have in Git Graph in the future, and I can see this likely being brought out of the backlog when prioritisation allows.

**Closed by mhutchie** 2020-12-11 23:46 UTC
Labels: backlog, feature request

**Comment by themightychris** [comment] 2020-12-12 23:54
I totally understand, thanks for the quick and thoughtful response!

**Comment by ankostis** [comment] 2021-10-08 07:40
(a big thank you for your efforts for this extension)
I cannot open a new VSCode window for the same folder - pressing `[Ctrl + N]` opens the new window but when i select the same folder, i get switched to the existing window.  I even tried in CLI to run the command `code --new-window some/folder` but still switched to the existing window.

So in all, i cannot workaround this feature-request with your suggested alternative, so it urge you to priortize this one.

My use-case is when exploring multitude of rebased-branches, and i want to see small diffs between same-named commits, so scrolling up/down makes it really hard to pin-point which one is which.

**Comment by absolutelysimon** [comment] 2021-12-13 22:37
Seconding ankostis' use case. We're having a problem with merging a rebased branch and it would be great to pull up multiple graphs at the same time!

**Comment by Mawos** [comment] 2023-04-03 17:08
Another upvote here. Regularly work in a codebase with a dozen repos, with code interaction between various pairs of repos. Would be very handy to be able to view the Git Graph on more than one repo at a time.

**Comment by vratojr** [comment] 2023-04-14 03:49
I upvote as well. @mhutchie you are doing a great job! But when you say:

> Based on prior conversations I've had with many users, and various other available metrics, I know that multi-root workspace > users are definitely a small portion of the Git Graph users. Out of this sub-group of users, your the first to raise that seeing two > repositories side-by-side would better suit your workflow 

Don't forget that there are also users around that are **not** using git graph because they are looking for a nice multi-root workspace tool. So maybe what you say it's true for the actual users but how many users out there are waiting for this feature? :) I, for instance, am! :) And I'm pretty sure that in a world evolving towards microservices (and tons of repositories) there a are a lot of persons that would profit from this...
