### ISSUE TITLE
cygwin64 compatibility "Unable to load Git Graph"

### ISSUE THREAD

**Issue by tagoresai** [mhutchie/vscode-git-graph#368] opened 2020-08-25 13:07 UTC
**Describe the Bug**
I installed cygwin in windows 10 and cloned my repository into it. I installed vscodium and added gitgraph extension. 
I added "git.path": "c:\\cygwin64\\bin\\git.exe" and "git-graph.maxDepthOfRepoSearch": 6 (not sure if this is needed) to settings.json.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Vscodium'
2. Click on 'gitgraph'
3. See error  "unable to load gitgraph"

**Environment**
 - Git Graph Extension Version: 1.24
 - VSCodium: 1.48.1
 - Operating System: Win10

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/70210029/91177849-53a34e80-e6b2-11ea-96fd-da92ea221c53.png)

![image](https://user-images.githubusercontent.com/70210029/91177883-60c03d80-e6b2-11ea-9f15-4d22820d7711.png)

**Comment by mhutchie** [comment] 2020-08-26 09:39
Hi @tagoresai,

This behaviour is unfortunately caused by `cygwin64` as follows:
1. When Git Graph scans the workspace for repositories on startup, it runs `git rev-parse --show-toplevel` (where `git` is the version specified by `git.path` if set). This is required to find the root of the repository.
    * On Windows, the standard Git executable would return a path like `c:/Users/Michael/Dev/vscode-git-graph`, however when using `cygwin64`, instead it returns a path like `/cygdrive/c/Users/Michael/Dev/vscode-git-graph`. This `/cygdrive/c/Users/Michael/Dev/vscode-git-graph` path is then recorded by Git Graph as the root of the repository.
2. When Git Graph attempts to run any Git command when opening the Git Graph View, it must run the commands from the root of the repository (i.e. `/cygdrive/c/Users/Michael/Dev/vscode-git-graph` according to `cygwin64`). However, this directory doesn't exist according to Windows, and will always throw an exception.
3. Because the exception indicates that the repository root (`/cygdrive/c/Users/Michael/Dev/vscode-git-graph`) doesn't exist, Git Graph automatically deletes it - hence "No Git repositories were found...".

Unfortunately this is just one of many compatibility issues with `cygwin64`. It's just not feasible for me to fully support `cygwin64` in Git Graph, as I can't support every non-standard version of Git on every platform (especially when most are extremely uncommon). I'd recommend you set `git.path` to a standard Windows Git executable if you want to use Git Graph for now _(see the next paragraph)_.

In saying that, completely independent of this bug I'm planning to migrate away from using `git rev-parse --show-toplevel` to find the root of the repository, as it has another limitation I'd like to avoid going forward. This bug strengths the case for migrating away from `git rev-parse --show-toplevel`. I plan to release this change in either the next version of Git Graph (released in the next two weeks), or the release immediately following it in a worst case scenario.

I'll close this bug for now, as complete compatibility with `cygwin64` is not something I believe I can feasibly support. However, I'll reply to this thread as soon as I release a version of Git Graph that no longer uses `git rev-parse --show-toplevel` (within the next three weeks), as it will make Git Graph better support `cygwin64` (however there's no guarantee that other compatibility issues won't exist). Once I've made this change, I'll have a look through other compatibility issues with `cygwin64`, and if feasible, I can re-open this issue & implement them.

**Closed by mhutchie** 2020-08-26 09:39 UTC
Labels: backlog, improvement, nice to have
