### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by manoj-apare** [mhutchie/vscode-git-graph#167] opened 2019-08-27 09:03 UTC
- Issue Type: `Performance`
- Extension Name: `git-graph`
- Extension Version: `1.13.0`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.37.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/kmanoj/mhutchie.git-graph-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mhutchie** [comment] 2019-08-27 09:33
Please provide the CPU Profile as required in the template you have used, so I can attempt to replicate the behaviour you have observed.

Also, please provide the following information to help me attempt to replicate & identify the cause of this:
* When did you get this? (e.g on VSCode startup, performing a specific task with Git Graph)
* Are you consistently getting this behaviour, or is it a one-off?

**Comment by mhutchie** [comment] 2019-08-29 06:58
As you haven't provided any information that can be used to replicate this issue, and no one else has reported any similar issues, I'm inclined to think this was an isolated one-off issue. As such, I'll close this issue as it is unreproducible.

If you are able to provide the information I requested, I'd be happy to look into it.

FYI: There is a new beta release available (unrelated to this issue) which has several fixes and improvements. You can download [v1.14.0-beta.2](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.14.0-beta.2), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Closed by mhutchie** 2019-08-29 06:58 UTC
Labels: needs more info
