### ISSUE TITLE
Empty window. Nothing loads

### ISSUE THREAD

**Issue by manecosta** [mhutchie/vscode-git-graph#460] opened 2021-02-10 00:08 UTC
I have this issue that when I open my projects in VSCode and open Git Graph, it always shows an empty window. Closing and reopening the Git Graph window has no effect. Restarting VSCode usually fixes it, however not if I do it quickly. Seems like some waiting is required, like leaving VSCode closed for a few seconds, and when opening it also waiting a few seconds before opening Git Graph.
I'm running Windows 10 and using WSL2, and I'm convinced the whole need to wait a bit is because WSL takes a bit to load within VSCode. I feel like Git Graph might be trying to access some resource (git I'd assume) before WSL is fully loaded within VSCode. It then crashes and never recovers.

Please let me know if there's a way I can provide more useful information like retrieving logs from somewhere.

**Environment**
 - Git Graph Extension Version: 1.28.0
 - Visual Studio Code Version: 1.53.1
 - Operating System: Windows 10 (WSL2)

**Screenshots**
![image](https://user-images.githubusercontent.com/1621485/107444773-1e40cf00-6b33-11eb-968f-2bb5fdc84322.png)

**Comment by mhutchie** [comment] 2021-02-10 00:13
Duplicate of #436.

Please see [my previous comment](https://github.com/mhutchie/vscode-git-graph/issues/436#issuecomment-744678297) for an explanation of what's occurring (you have cause 2) - this is a known Visual Studio Code WSL Webview bug, that affects all extensions that use Webview's (not just Git Graph).

**Closed by mhutchie** 2021-02-10 00:13 UTC
Labels: bug

**Comment by manecosta** [comment] 2021-02-10 00:35
Thanks for the quick answer. It seems like the workaround doesn't work anymore on recent versions. However some movement has just happened on the vscode bug in the past hour incidentally. Hopefully it leads to a fix. Keep up the great work!

**Comment by barroudjo** [comment] 2021-02-19 14:13
Just to let you guys know, this is fixed in vscode insiders 1.54.0. So it should be fixed in the general version pretty soon !

**Comment by mhutchie** [comment] 2021-02-19 20:46
Hi @barroudjo,

Thank you for letting us know, it’s great news that this bug (that’s been around in Visual Studio Code for such a long time) has finally been fixed!
