### ISSUE TITLE
Support for multi-root workspaces, with multiple git repositories

### ISSUE THREAD

**Issue by axetroy** [mhutchie/vscode-git-graph#13] opened 2019-02-25 13:32 UTC
**Describe the feature that you'd like**
When there are multiple workspaces, the default workspace will only be resolved by default.

But this is not what we want, we need to be able to select the specified workspace and parse.

For example, open the terminal.

There will be a popup window in which workspace to open

![2019-02-25 21 31 34](https://user-images.githubusercontent.com/9758711/53340780-c4926a80-3944-11e9-9d82-c785353f41a1.png)

**Additional context (optional)**
none!

**Comment by mhutchie** [comment] 2019-02-27 20:54
I’m definitely adding support for this functionality soon. v1.4.0 is going to be released in the next two days which has a quite distint set of new features, this will be available in the next release after v1.4.0. It will focus on changes in the top control bar, which is where you’ll then be able to select the desired git repository when multiple are present in the VSCode workspace.

**Comment by mhutchie** [comment] 2019-03-09 06:59
This is now completed and will be available in 1.4.1, which will be released in the next few hours.

**Closed by mhutchie** 2019-03-09 06:59 UTC
Labels: feature request

**Comment by asierralozano** [comment] 2019-03-15 09:25
Hello!
I have the following structure in my VsCode project:

- Folder1 (is not a git repo)
-- library1 (is a git repo)
-- library2 (is a git repo)
-- .. (some more git repos)

- Folder2 (is not a git repo)
-- library1 (is a git repo)
-- library2 (is a git repo)
...

The problem is that the extension is not recognizing the Git repos, and it is only showing me the main one.

PD: Sorry for reopening the issue. I can open a new one if you want.

**Comment by mhutchie** [comment] 2019-03-15 09:48
@asierralozano This issue was focused on extending support to multi-root workspaces, where each root is either a git repo or not. Could you please open a new issue for "Support for git repositories in subfolders", so I can track the feature request, as it will be in a future release? Thank you!

**Comment by asierralozano** [comment] 2019-03-15 09:53
Of course! Thanks mate!
