### ISSUE TITLE
🐛 Scale proportionally the tree icon of vscode-git-graph

### ISSUE THREAD

**Issue by alexandre-eliot** [mhutchie/vscode-git-graph#512] opened 2021-05-14 09:57 UTC
**Describe the Bug**
In the _Source Control_ panel, on any tab of any repository; the tree icon of vscode-git-graph is almost too small to click on.

**Environment**
- Having a git repository recognised in the _Source Control_ panel

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Have a git repository opened in vscode's workspace
2. Go to on the _Source Control_ panel

**Expected Behaviour**
The icon of vscode-git-graph is visible and easily clickable

**Environment**
 - Git Graph Extension Version: 1.30.0
 - Visual Studio Code Version: 1.56.1
 - Operating System: WSL - Ubuntu 20.04

**Screenshots**
![capture](https://user-images.githubusercontent.com/61505773/118253905-c5befc00-b4aa-11eb-9523-7b0bf908cee7.png)

**Additional Context**
- Windows display scaling: 100%

**Comment by mhutchie** [comment] 2021-05-14 10:10
This is a duplicate of #502 - this was introduced as a bug in Visual Studio Code 1.56.0 last week.

It has since been fixed in Visual Studio Code 1.56.2, please update Visual Studio Code to resolve this issue.

**Closed as completed by mhutchie** 2021-05-14 10:10 UTC
Labels: vscode-bug, duplicate
