### ISSUE TITLE
Git Graph doesn't show the repository after changing its name.

### ISSUE THREAD

**Issue by Heeam-Shin** [mhutchie/vscode-git-graph#443] opened 2020-12-21 01:29 UTC
**Describe the Bug**
After changing the name of directory (which contains `.git` file), Git Graph doesn't show the repository of the directory.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Clone any repository.
2. Open Git Graph and check the repository.
2. Change the name of repository's root directory.
3. Open Git Graph. It doesn't show the repository.

**Expected Behaviour**
Even if the name of root direcotory is changed, the repository still shows in Git Graph.

**Environment**
 - Git Graph Extension Version: 1.28.0
 - Visual Studio Code Version: 1.51.1
 - Operating System: Windows 10

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment] 2020-12-21 02:10
Git Graph identifies repositories by the path of it's repository root on the file system, as it's the only way to uniquely identify a repository on the file system.

If you rename a repository on the file system, the extension will think the repository was deleted (because the old repository root no longer exists on the file system), and therefore remove it. There is no way of knowing that the new name of a repository is actually the same as a previously known repository (it has a different repository root).

If you want to add the renamed repository back into Git Graph, you can either:
* Manually add it, by running the "Git Graph: Add Git Repository..." command from the Visual Studio Code Command Palette.
* Reload Visual Studio Code. On Visual Studio Code start-up, Git Graph will rescan the file system within the workspace for new repositories, and automatically add it/them in Git Graph (this would find the renamed repository). If you use this approach, and the repository is not at the root of the Visual Studio Code Workspace, you need to ensure `git-graph.maxDepthOfRepoSearch` is set correctly.

I'll close this issue, as it is the expected (unavoidable) behaviour, and not a bug. There is also no way to improve the behaviour of Git Graph in this scenario.

**Closed by mhutchie** 2020-12-21 02:10 UTC
Labels: question

**Comment by Heeam-Shin** [comment] 2020-12-21 02:24
@mhutchie,
Thanks for the quick answer. Both workarounds work fine!
