### ISSUE TITLE
Git graph doesn't open anymore

### ISSUE THREAD

**Issue by alexandreDavid** [mhutchie/vscode-git-graph#530] opened 2021-06-22 09:01 UTC
Issue Type: <b>Bug</b>

When I click on the button, I have this message:
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

Extension version: 1.30.0
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.8.0-55-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 3316)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.48GB (1.15GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 5e05b36d-33e3-40aa-ac9d-4ce1395aeb6b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
binariesv615:30323119
vsccppwt:30322536

```

</details>

**Comment by mhutchie** [comment] 2021-06-22 09:16
Duplicate of #524 - this is a known Visual Studio Code Bug that Microsoft is aware of.

**Closed as completed by mhutchie** 2021-06-22 09:16 UTC
Labels: vscode-bug, duplicate
