### ISSUE TITLE
Error loading webview

### ISSUE THREAD

**Issue by tritemio** [mhutchie/vscode-git-graph#511] opened 2021-05-13 14:21 UTC
**Describe the Bug**
With VS code 1.56.1 git graph does not work showing the message:

```
Error loading webview: Error: Could not register service workers: 
InvalidStateError: Failed to register a ServiceWorker: 
The document is in an invalid state..
```

**Steps to Reproduce**
Use VS Code 1.56.1, click on the git graph icon

**Expected Behaviour**
See the git graph

**Environment**
 - Git Graph Extension Version: 1.30.0
 - Operating System: Ubuntu 2020.04

vs code:
```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-50-generic snap
```

**Screenshots (optional)**
Add any screenshots showing the bug.

**Additional Context (optional)**
Downgrading to vs code 1.55.2 fixes the issue.

**Comment by Daners** [comment] 2021-05-13 17:55
duplicate bug #508 [apparently it is a bug in VScode](https://github.com/mhutchie/vscode-git-graph/issues/508#issuecomment-839541139)

**Comment by mhutchie** [comment] 2021-05-13 22:26
Hi @tritemio,

This is a duplicate of #508, please read my [previous comment](https://github.com/mhutchie/vscode-git-graph/issues/508#issuecomment-839541139). It's one of several bugs that Visual Studio Code introduced in 1.56.x that affected all extensions that use a number of Visual Studio Code API integrations.

**Closed as completed by mhutchie** 2021-05-13 22:26 UTC
Labels: vscode-bug, duplicate

**Comment by tritemio** [comment] 2021-05-14 09:23
@mhutchie thanks for pointing me to the correct issue. I apologize for the noise, and thanks for this great extension!

**Comment by tritemio** [comment] 2021-05-14 09:25
@Daners did you open an issue upstream for vs code? If yes, can you please link the issue here?
