### ISSUE TITLE
New Window shortcut opens 2(two) new windows when Git Graph is active window in editor

### ISSUE THREAD

**Issue by rje6459** [mhutchie/vscode-git-graph#102] opened 2019-06-11 14:26 UTC
Issue Type: <b>Bug</b>

1. Open folder with git repo
2. Install Git Graph extension
3. Open Source Control
4. Click View Git Graph
5. Press New Window keyboard shortcut

![vscode-git-graph-issue](https://user-images.githubusercontent.com/16375649/59280336-68253380-8c33-11e9-80b1-0814782276a6.gif)

Extension version: 1.8.0
VS Code version: Code - Insiders 1.36.0-insider (7bc29bf67c17608b11e23a8497c8f1de5a0922cf, 2019-06-11T08:24:45.384Z)
OS version: Linux x64 5.1.7-300.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 2267)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.74GB (0.12GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mhutchie** [comment] 2019-06-12 00:05
Thanks for raising this bug! 

I was unable to replicate this behaviour following the scenario you provided on Windows or Mac with both the Standard or Insider Visual Studio Code releases (I don't have access to a Linux machine to replicate it on Linux). This would imply it only occurs on Linux.

I expect that this bug would occur for any extension contributing a [Webview](https://code.visualstudio.com/api/extension-guides/webview), when the Webview is open. Git Graph doesn't have anything to do with Visual Studio Code commands / shortcuts like opening a new window, or window management. Therefore I believe it is not a bug in Git Graph, and is a bug in the Insider release of Visual Studio Code caused by something that Git Graph uses (e.g. Webview's). Other issues affecting all extensions using Webview's have happened before with Insider builds, i.e. it's not uncommon.

I'd suggest installing another extension that uses a Webview, such as [Edit csv](https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv), to see if you can observe the same behaviour with it.

I'm closing this issue for now as there is no way I could fix this behaviour from within the Git Graph codebase, and it would have to be fixed in Visual Studio Code itself.  Please raise it as a bug in the https://github.com/Microsoft/vscode repository, so they can be made aware of it & fix it.

Please let me know what you find out, I'd be curious to know what caused this issue.

**Closed by mhutchie** 2019-06-12 00:05 UTC

**Comment by rje6459** [comment] 2019-06-13 12:55
@mhutchie, I think you've hit the nail on the head on it being a Webview problem. After I had installed the Edit csv extension you recommended to test, I tried opening a new VSCode window and the Webview on the extension page triggered the bug. I'll go ahead an open a bug on the main vscode repository. Thanks!

**Comment by mhutchie** [comment] 2019-06-13 13:06
Thanks for letting me know!
