### ISSUE TITLE
Extension doesn't work with vscode-insider: Git Graph、Edit csv.

### ISSUE THREAD

**Issue by iFanze** [mhutchie/vscode-git-graph#80] opened 2019-05-18 09:07 UTC
Issue Type: <b>Bug</b>

These extensions do work before I reset my Windows 10. But after I reset my Windows, reinstall my softwares including vscode-insider.  I cannot use these  extensions with Remote - SSH on the remote side. I take the screenshots.

![image](https://user-images.githubusercontent.com/6697503/57967273-5a132880-798f-11e9-9dc8-5a09c70eaae0.png)
![image](https://user-images.githubusercontent.com/6697503/57967276-67301780-798f-11e9-89f0-c92e7975fa24.png)

Extension version: 1.5.0
VS Code version: Code - Insiders 1.35.0-insider (6ac87465f297a9068bf767f45d6f372fc5697de9, 2019-05-17T17:48:07.036Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 2.6.32-573.el6.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (12.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 192.168.22.51|
|OS|Linux x64 2.6.32-573.el6.x86_64|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|15.44GB (5.93GB free)|
|VM|0%|
</details>

**Comment by mhutchie** [comment] 2019-05-19 04:30
I've tested the extension with VS Code Insiders 1.35.0 (at the same commit hash you specified), and it is working fine for me. As multiple extensions are not working for you, it appears to be an issue with your setup, and not Git Graph specifically.

Just from the screenshots you provided I can see that the base HTML page rendered in the [Webview](https://code.visualstudio.com/api/extension-guides/webview) is correctly produced by the extensions, but the JS & CSS used to render and style the UI cannot be loaded. I would guess that it may be caused by a permissions issue on the VS Code extension folder preventing JS & CSS from loading. I'm not sure what else could cause this issue for you.

I'm closing this issue as it is not caused by the Git Graph extension.

**Closed by mhutchie** 2019-05-19 04:30 UTC

**Comment by mhutchie** [comment] 2019-05-20 00:06
I've found out more information regarding the "Remote Development" functionality available in the vscode-insiders release, which I now realise you are referencing.  Support for "Remote Development" is not currently available in Git Graph, as it requires a fundamental change in how the JS & CSS are loaded (as they are stored on the remote system instead of the local machine).

Feature request #83 will add this functionality, and will be released either at the end of this week (ideally), or the end of next week.

@Dontar has kindly created an initial implementation of this functionality in PR #84 that will allow you to use the "Remote Development" functionality right away, although its current performance will be improved before it is released in Git Graph.
