### ISSUE TITLE
Reopen Git Graph tab when VS Code is reloaded/re-opened

### ISSUE THREAD

**Issue by ginomempin** [mhutchie/vscode-git-graph#276] opened 2020-03-09 00:25 UTC
**Describe the improvement that you'd like**

1. When VS Code is reloaded (ex. Command Palette > Reload Window) with the Git Graph tab opened, include it in the auto-reloaded tabs.
1. When VS Code was originally closed with the Git Graph tab opened, re-opening the app with restore windows functionality enabled should also re-open the Git Graph tab.

Basically, if the last state is that the Git Graph was opened, it should be automatically re-opened along with all the other editor tabs.

**Additional context (optional)**

I could not find a setting to have this behavior.  
All my other editor tabs are re-opened when VS Code is reloaded/re-opened.  
All except for the Git Graph tab.

Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:50:36.977Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.15.0-88-generic

**Comment by mhutchie** [comment] 2020-03-09 07:02
Thanks for raising this improvement request!

I initially wanted to provide this functionality almost a year ago, however when I implemented it I found there was an unavoidable issue with how Visual Studio Code implements Webview’s (which the Git Graph View uses for rendering). The limitation is restricted to Webview’s contributed by any extension, which is why all of the Text Editors and Visual Studio Code contributed Webview’s work fine.

I’ve been waiting for Visual Studio Code to address the underlying core functionality required for this feature to function smoothly. Once Microsoft has provided it, I have the code already implemented and ready to merge & release.

I’ll close this improvement request temporarily (and label it as a “backlog” item) until Microsoft provides the functionality. Once they do, I’ll re-open this request and include it in the soonest possible release.

**Closed by mhutchie** 2020-03-09 07:02 UTC
Labels: improvement

**Comment by borisghidaglia** [comment] 2022-07-21 10:56
@mhutchie if you identified specific vscode issues or PR that need to be implemented/merged in order to make this feature possible, don't hesitate to paste them here so that we can show our support over there.

Plus, your extension has 3m+ downloads (congrats and thank you!), so it might be a good argument 🤷🏻‍♂️🤞

**Comment by t0b1hh** [comment] 2022-09-01 14:31
any updates on this? 🥺

**Comment by jibbers42** [comment] 2023-11-13 06:00
https://github.com/mhutchie/vscode-git-graph/issues/276#issuecomment-596361340 doesn't actually say what the issue is. Has the status been checked in a while? Is there a vscode issue that can be shared so we can see the status?

If it's a timing thing, can Git Graph show empty/loading content while waiting for whatever resource/subsytem isn't available, then show the graph when the resource is available?
