### ISSUE TITLE
Keep the header on top

### ISSUE THREAD

**Issue by jsg2021** [mhutchie/vscode-git-graph#478] opened 2021-03-12 07:00 UTC
It would be nice to have a sticky header so it wouldn't scroll off screen.

**Comment by mhutchie** [comment] 2021-03-12 07:10
Closing, as this is a duplicate of #132.

**Closed by mhutchie** 2021-03-12 07:10 UTC
Labels: duplicate

**Comment by jsg2021** [comment] 2021-03-12 07:13
sorry for the dupe! 😊 I should have searched harder😊
