### ISSUE TITLE
Add "Push" button in top left of tool bar

### ISSUE THREAD

**Issue by hienlh** [mhutchie/vscode-git-graph#328] opened 2020-06-21 11:09 UTC
**Describe the feature that you'd like**
Dear, 

I want a "Push" button in top left of tool bar (please check the screenshot). Because sometimes after I commit somethings by default git tool of vscode, I want to push this commit with one click. But currently I have to right click to branch to push it. This took me more time.

So please consider my request.
Thanks.

**Additional context (optional)**
![DeepinScreenshot_select-area_20200621180053](https://user-images.githubusercontent.com/36977998/85222975-6024d580-b3e9-11ea-9e05-a141f49d8ec2.png)

**Comment by mhutchie** [comment] 2020-06-21 11:42
I'm closing this feature request as it is a duplicate of #195, which was closed and moved to the backlog for the reasons detailed in [my response](https://github.com/mhutchie/vscode-git-graph/issues/195#issuecomment-539826050).

**Closed by mhutchie** 2020-06-21 11:42 UTC
Labels: feature request
