### ISSUE TITLE
Version 1.19.0 doesn't work in WSL anymore

### ISSUE THREAD

**Issue by michaelschufi** [mhutchie/vscode-git-graph#221] opened 2019-11-27 09:07 UTC
**Describe the Bug**

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Install 1.19.0 on WSL
2. Notice that "Git Graph" in the status bar is missing.
3. Go to the Source Control Tab
4. Click on the Git Graph icon at the top
5. Receive an error `command 'git-graph.view' not found`

**Expected Behaviour**
Like on Windows 10 the Git Graph extension should open. 1.19.0 is working just fine on Windows.

**Environment**
 - Git Graph Extension Version: 1.19.0
 - Visual Studio Code Version: 1.40.2
 - Operating System: Windows 10

**Additional Context**
Installing 1.18.0 still works just fine. (After disabling the auto update, obv.)

**Comment by mhutchie** [comment] 2019-11-27 09:20
Thanks for reporting this!

I've identified the cause of this issue as the changes made to support #209. I'll have a patch release available soon that resolves this.

**Comment by mhutchie** [comment] 2019-11-27 10:27
This has just been released in v1.19.1.

**Closed by mhutchie** 2019-11-27 10:27 UTC
Labels: bug

**Comment by mhutchie** [comment] 2019-11-27 10:42
@michaelschufi Please try out the patched released, and confirm that it has fixed the issue for you.

If you haven't received the update notification, you can:
1. Open the Visual Studio Code Extension Panel
2. Click on the "..." button (More actions...)
3. Select "Check for Extension Updates"

**Comment by michaelschufi** [comment] 2019-11-27 19:22
Looks good to me  👍 
Thanks :D
