### ISSUE TITLE
Graph fails to render in WSL after upgrade to WSL 2

### ISSUE THREAD

**Issue by jpoles1** [mhutchie/vscode-git-graph#382] opened 2020-09-17 19:33 UTC
**Describe the Bug**
I've been using Git Graph for some time now, and have really loved it, thank you so much for the amazing extension. Yesterday, I just upgraded from using WSL1 to WSL2, and now the graph fails to render when using the Remote-WSL environment. If I switch back to Windows it works just fine. 

**Steps to Reproduce**
Steps to reproduce the behaviour:
1) Using WSL2, open linux terminal
2) code . (in folder with git repo)
3) Open git graph from the button in the source controls sidebar

**Expected Behaviour**
Display git graph

**Environment**
 - Git Graph Extension Version: 1.26
 - Visual Studio Code Version: 1.49
 - Operating System: Win 10, WSL2, Ubuntu 18.04

**Screenshots**
![Capture](https://user-images.githubusercontent.com/366282/93518182-7c59e500-f8fa-11ea-959e-a1a84d5620b9.PNG)

**Comment by mhutchie** [comment] 2020-09-17 21:23
I'm closing this, as it is a Visual Studio Code Bug and is a duplicate of #378 (and numerous others).

I've included you in the Visual Studio Code Bug raised by another Git Graph user, so you can receive updates on its delivery.

**Closed by mhutchie** 2020-09-17 21:23 UTC
Labels: vscode-bug
