### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mmoncalvo** [mhutchie/vscode-git-graph#140] opened 2019-07-22 19:08 UTC
- Issue Type: `Performance`
- Extension Name: `git-graph`
- Extension Version: `1.12.0`
- OS Version: `Darwin x64 15.6.0`
- VSCode version: `1.36.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/Marco/mhutchie.git-graph-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mhutchie** [comment] 2019-07-22 21:46
Can you please attach the cpuprofile as highlighted in the template you have used so I can investigate the cause of this issue for you.

Also, please provide the following information to help me attempt to replicate & identify the cause of this:
* When did you get this? (e.g on VSCode startup, performing some task with Git Graph)
* Are you consistently getting this behaviour, or is it a one-off?

**Comment by mhutchie** [comment] 2019-07-24 22:56
As you haven't provided any information that can be used to replicate this issue, and no one else has reported any similar issues, I'm inclined to think this was an isolated one-off issue. As such, I'll close this issue as it is unreproducible.

If you are able to provide the information I requested, I'd be happy to look into it.

**Closed by mhutchie** 2019-07-24 22:56 UTC
Labels: needs more info
