### ISSUE TITLE
See files in activity bar on commit click

### ISSUE THREAD

**Issue by DavidBabel** [mhutchie/vscode-git-graph#509] opened 2021-05-12 10:25 UTC
**Describe the feature that you'd like**
It would be amazing to access the changes for a commit (when click on it) to a dedicated activity which lists the modified file for this commit (the same way the default git activity does).

This app also deserve it's own icon int the sidebar liked to this activity bar and the graph ui itself <3

**Comment by mhutchie** [comment] 2021-05-12 11:10
Hi @DavidBabel,

I'll close this as I believe it is a duplicate of #438 & #75. Please provide further clarification if I've misinterpreted your request.

**Closed as completed by mhutchie** 2021-05-12 11:10 UTC
Labels: feature request, duplicate
