### ISSUE TITLE
status bar branch update

### ISSUE THREAD

**Issue by caasi-dev** [mhutchie/vscode-git-graph#282] opened 2020-03-21 14:20 UTC
**Describe the Bug**
When checking out the branches using Git Graph, it does not seem to update main VSCode status bar. It's rather inconsistent and I cannot establish the pattern when it actually happens, but sometimes it seems as VSCode status bar hangs and it does not refresh.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Open VSCode
2. Open project
3. Open GitGraph
4. Checkout few branches on GitGraph

**Expected Behaviour**
Status bar should be updated with currently checked out branch

**Environment**
 - Git Graph Extension Version: 1.22.0
 - Visual Studio Code Version: 1.43.1
 - Operating System: Ubuntu 20.04. Arch Linux (both fully updated)

**Screenshots (optional)**
![isseu1](https://user-images.githubusercontent.com/60949037/77228385-eb8a9280-6b7e-11ea-81d0-2814dd0adc66.png)
![issue2](https://user-images.githubusercontent.com/60949037/77228386-ecbbbf80-6b7e-11ea-8acd-2f06c15a3788.png)

**Comment by mhutchie** [comment] 2020-03-21 20:13
This issue is a duplicate of #280 & #275 (raised during the last two weeks).

After running the Checkout Branch command, because the branch label is bolded and has a coloured outline it indicates that the branch was checked out by Git, and when the Git Graph View automatically refreshed, Git confirmed the branch was successfully checked out. This indicates that Git Graph is functioning completely as expected, the branch was checked out in the repository immediately when you ran the action.

The Visual Studio Code Git Extension (which contributes the Git View & the Status Bar Item you’re referring to) monitors File System events in the repository to background refresh and reflect the currently checked out branch. File System event monitoring in Visual Studio Code is notoriously unpredictable (there are many factors that can influence it).

Visual Studio Code's monitoring of the repository (and consequent updates to their Git UI & Status Bar Item) is completely unrelated to Git Graph. There also isn't anything I can do in Git Graph to make Visual Studio Code refresh more consistently / faster after the repository changes (e.g. after a branch is checked out).

FYI: You should be able to observe the same delayed updates of Visual Studio Code's Git UI & Status Bar item if you run the Git command `git checkout <other-branch>` in a terminal window. *(this is all that Git Graph is doing when you run the checkout branch action)*

I'll close this issue as it is unrelated to Git Graph, and I'm unable to make any changes that would make Visual Studio Code update any faster. An issue has already been raised in the Visual Studio Code repository, so hopefully they will resolve it soon.

**Closed by mhutchie** 2020-03-21 20:13 UTC
Labels: bug

**Comment by caasi-dev** [comment] 2020-03-22 09:38
Thanks for comprehensive explanation. I did not doubt GitGraph for a second because it's working as intended, i just thought there was closer relation to VSCode components. Sorry for not spotting the issue in closed ones.
