### ISSUE TITLE
Toolbar and table header should stay fixed at top when scrolling

### ISSUE THREAD

**Issue by austincondiff** [mhutchie/vscode-git-graph#566] opened 2021-09-16 23:08 UTC
The toolbar and table header should stay fixed at top when scrolling down the git graph. If I am clear down the page and I want to make a new selection, I need to scroll all the way up to make my selection. As you are aware, git graph is in vscode which is an application with fixed panes and toolbars. This extension should follow the same pattern and feel as native to vscode as possible.

**Comment by mhutchie** [comment] 2021-09-16 23:36
Duplicate of #132

**Closed as completed by mhutchie** 2021-09-16 23:36 UTC
Labels: duplicate
