### ISSUE TITLE
Issue Linking: Support for Multiple Issue Tracking System

### ISSUE THREAD

**Issue by gianlucaparadise** [mhutchie/vscode-git-graph#451] opened 2021-01-15 13:54 UTC
**Describe the feature that you'd like**
Add the possibility to configure multiple Issue Tracking System.

**Additional context**
My team is using two Issue Tracking Systems and it would be useful to add a list of pair of _Issue Regex_ and _Issue URL_. This would let us match multiple IDs and for each matched ID use the URL for the correct Issue Tracking System.

**Comment by mhutchie** [comment] 2021-01-15 20:34
Hi @gianlucaparadise,

Thanks for raising this feature request, this is definitely a capability I want to implement in Git Graph!

I’ll close this request, as it’s a duplicate of the existing feature request #313.

**Closed by mhutchie** 2021-01-15 20:34 UTC
Labels: feature request
