### ISSUE TITLE
vscode-insiders: Webview contents not loading

### ISSUE THREAD

**Issue by morganlombard** [mhutchie/vscode-git-graph#317] opened 2020-06-02 13:24 UTC
**Describe the Bug**
With the latest VSCode insider release Version: 1.46.0-insider the graph does not show. The Git Graph panel opens, only showing
Repo:
Branches:
[Checkbox] Show Remote Branches 

This is both Windows 10 and Ubuntnu 20.04

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Open VSCode
2. Click on 'Git Graph' in bottom left of status bar
3. Do not see Graph.

**Expected Behaviour**
Expect to see a Graph of commits and branches.

**Environment**
Ubuntu 20.04
Version: 1.46.0-insider
Commit: 1bfa086adb9271ff56be11821da686e4cfffb672
Date: 2020-06-02T06:55:30.074Z
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-33-generic
Git Graph v1.23.0

Windows 10
Version: 1.46.0-insider (system setup)
Commit: 1bfa086adb9271ff56be11821da686e4cfffb672
Date: 2020-06-02T06:55:33.079Z
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
Git Graph v1.23.0

**Screenshots (optional)**
![Screenshot from 2020-06-02 15-22-22](https://user-images.githubusercontent.com/1935714/83525279-09606600-a4e5-11ea-87f7-20c83b4dd651.png)

**Comment by mhutchie** [comment] 2020-06-02 21:32
Hi @morganlombard,

I believe this is being caused by #305 (please read the full thread for more context of this change). Provided this is what's occurring (seems highly likely), I'll have a beta fix available for this soon.

**Comment by mhutchie** [comment] 2020-06-02 22:01
After making the vscode team aware of this bug, they have implemented a fix to resolve it (as it relates to all extensions that use a [Webview](https://code.visualstudio.com/api/extension-guides/webview)). It will hopefully be included in the next vscode-insiders build, which will allow Git Graph to work again in vscode-insiders.

**Comment by xiaoyongdong** [comment] 2020-06-03 07:07
Same in today's vscode-insiders build.

**Comment by matthewapeters** [comment] 2020-06-03 22:18
"Me too" on OSx:

```
Version: 1.46.0-insider
Commit: 595d2b9b916d063aadfc2c1a8c8f6df5b45572a8
Date: 2020-06-03T05:38:33.098Z (16 hrs ago)
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**Comment by mjbvz** [comment] 2020-06-04 00:35
This should be fixed in the next VS Code insiders (I fixed the original bug the caused this yesterday and then proceeded to break it again in an interesting new way!)

**Comment by HalfBottleOfMind** [comment] 2020-06-04 10:03
Fixed in
```
Version: 1.46.0-insider (user setup)
Commit: c7a37c4400bb4c1b92eeeaea1bcacc9ec3789ef3
Date: 2020-06-04T08:37:48.091Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by mhutchie** [comment] 2020-06-05 06:56
Closing this now, as it has been fixed in the latest vscode-insiders build for almost a day now.

**Comment by volopasse** [comment] 2020-06-20 20:24
FYI for anyone coming across this issue, seems to have regressed in 1.47.x

```
Version: 1.47.0-insider (user setup)
Commit: b9d7ec9ff367a8e59fe4cc2abee605a55be180e8
Date: 2020-06-20T00:08:33.687Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by Smoovsky** [comment] 2020-06-24 05:24
> FYI for anyone coming across this issue, seems to have regressed in 1.47.x
> 
> ```
> Version: 1.47.0-insider (user setup)
> Commit: b9d7ec9ff367a8e59fe4cc2abee605a55be180e8
> Date: 2020-06-20T00:08:33.687Z
> Electron: 7.3.1
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.19041
> ```

Yes, experiencing the same problem in the latest insider's build

**Comment by mhutchie** [comment] 2020-06-24 08:27
@mjbvz The bug described below is preventing all Git Graph users that use Visual Studio Code Insiders from using the extension (and affects all extensions that use Webview's) - it is different from the bug you previously fixed. Here's some additional background information:

Starting around Visual Studio Code 1.43.0 (give or take a release), immediately after the vscode release some users intermittently observed that Visual Studio Code would fail to load resources via the vscode-resource scheme. I can also confirm that it occurred using the old direct-set method of vscode-resource, and using the new asWebviewUri method. It has been reported by users on Windows, Mac & Ubuntu (so isn't platform specific). It was fixed for about three weeks, and just a few days ago it started to intermittently affect users. However, in today's insiders build, it seems to not work for everyone, I've got heaps of reports of it.

![image](https://user-images.githubusercontent.com/5315753/85519976-a1b1bc80-b645-11ea-9fe5-617f6b6ef8c6.png)

**Comment by JustinGrote** [comment] 2020-06-24 20:22
+1 for me:
![image](https://user-images.githubusercontent.com/15258962/85623796-cd20b100-b61d-11ea-8c15-9b78af4f6152.png)

**Comment by JustinGrote** [comment] 2020-06-26 05:36
@mhutchie latest insiders works again for me in newest 1.47.0-insider released today
![image](https://user-images.githubusercontent.com/15258962/85824311-5cb88380-b734-11ea-86a9-c8dc225e91da.png)

**Comment by mhutchie** [comment] 2020-06-26 07:31
It seems to be broken again in the next Insiders build:

Version: 1.47.0-insider (user setup)
Commit: 6c235c723cb2d8defb840f732eac620f54aa8b9d
Date: 2020-06-26T06:20:06.931Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by cmendible** [comment] 2020-06-26 07:41
Yep, @mhutchie I can confirm that it's broken again...

Version: 1.47.0-insider (user setup)
Commit: 6c235c723cb2d8defb840f732eac620f54aa8b9d
Date: 2020-06-26T06:20:06.931Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by mhutchie** [comment] 2020-06-26 08:08
I've raised this with Microsoft again, hopefully it will be fixed soon...

**Comment by mhutchie** [comment] 2020-06-26 22:58
Webviews are now working again in Visual Studio Code Insiders:
* Version: 1.47.0-insider (user setup)
* Commit: 9bf6af04dcb5c2e531cedca83cd188939ca1b0db
* Date: 2020-06-26T18:55:07.038Z
* Electron: 8.3.3
* Chrome: 80.0.3987.165
* Node.js: 12.13.0
* V8: 8.0.426.27-electron.0
* OS: Windows_NT x64 10.0.18362

**Closed by mhutchie** 2020-06-26 22:58 UTC
Labels: vscode-bug

**Comment by JustinGrote** [comment] 2020-06-27 00:07
@mhutchie confirmed working for me, thanks for going to bat with the code team on that one.

**Comment by volopasse** [comment] 2020-06-27 10:58
Sadly doesn't work here:

```
Version: 1.47.0-insider (user setup)
Commit: 9bf6af04dcb5c2e531cedca83cd188939ca1b0db
Date: 2020-06-26T18:55:07.038Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19042
```

The difference with above may be that I'm using it in WSL. Also the error is slightly different:
![](https://imgur.com/a/vDSBWy4)

**Comment by mhutchie** [comment] 2020-06-27 11:54
@volopasse I've just tried Git Graph in WSL with the same Visual Studio Code Insiders release as you're using and everything is working fine for me.

What is the full path of `out.min.css` & `out.min.js`, and can you locate it on the file system?

**Comment by volopasse** [comment] 2020-06-27 12:04
Yep, both files are in `~/.vscode-server-insiders/extensions/mhutchie.git-graph-1.24.0/media`. Both have contents in the file system, as in they are not empty. However, in the resource viewer the `.css` is blank

![git-graph-resources](https://user-images.githubusercontent.com/2857268/85921716-23882c80-b876-11ea-9300-fe5bdccc0cb0.png)

![git-graph-path](https://user-images.githubusercontent.com/2857268/85921717-26831d00-b876-11ea-9412-0d1af21b7e3b.png)

I might spin up a new WSL  with another distro to see if it persists

**Comment by mhutchie** [comment] 2020-06-27 12:09
@volopasse That's really interesting, it would be great if you could spin up a new WSL and see if it persists.

**Comment by volopasse** [comment] 2020-06-27 12:24
Spun up a brand new WSL (Ubuntu 20), same thing, 404's on the two network resources. `Output > Git Graph` appears to process the repo correctly:
```
[2020-06-27 13:14:51.145] Starting Git Graph ...
[2020-06-27 13:14:51.166] Using git (version: 2.25.1)
[2020-06-27 13:14:51.170] Started Git Graph - Ready to use!
[2020-06-27 13:14:51.171] Searching workspace for new repos ...
[2020-06-27 13:14:51.175] > git rev-parse --show-toplevel
[2020-06-27 13:14:51.209] Added new repo: /home/volopasse/gitgraph-test
[2020-06-27 13:14:51.211] Completed searching workspace for new repos
[2020-06-27 13:14:51.211] Showing "Git Graph" Status Bar Item
[2020-06-27 13:14:52.397] Created Git Graph View
```
But nothing shows up because the resources could not be loaded

VSCode Release (with the following build details) loads the same repo correctly. However, the URIs are different: Release version has `vscode-resource://file///<path>`, Insiders has `vscode-webview-resource://<some uuid>/file///<path>`. Anything else I can give you to help troubleshoot?

**Comment by mhutchie** [comment] 2020-06-27 12:50
@volopasse, Thanks for the additional information. I've been experimenting and still can't observe the 404's you're getting in WSL.

The team at Microsoft have been been rewriting the Webview implementation this iteration, which has been causing all of the bugs we've had recently in the Visual Studio Code Insiders build.

The URI scheme change from `vscode-resource://file///<path>` to `vscode-webview-resource://<some uuid>/file///<path>` is just one of these changes. This scheme change has been working for me on Windows, Mac, Windows WSL & Mac Docker, so it shouldn't be the cause.

Would you mind raising this Visual Studio Code Insiders WSL Webview issue you're observing to the [vscode team](https://github.com/microsoft/vscode/issues)? With all their Webview changes it seems highly likely that this is a bug that they need to resolve. If it's affecting you using Git Graph, it will likely be affecting others who use WSL and any of the extensions that use Webviews. I'll keep an eye out for it, and will provide additional assistance if necessary.

**Comment by volopasse** [comment] 2020-06-27 12:55
Absolutely, will do. I appreciate there's not much you can do if it's upstream of your code, and you can't observe it yourself!

**Comment by volopasse** [comment] 2020-06-29 14:48
Managed to narrow it down, turns out the issue is specifically with WSL2! Now [posted](https://github.com/microsoft/vscode/issues/101272) on the VSCode issue tracker

**Comment by mhutchie** [comment] 2020-06-30 07:52
Thanks @volopasse, that’s really useful to know if anyone else is having this issue!

**Comment by LongLiveCHIEF** [comment] 2020-06-30 12:31
I don't think it's specifically for WSL2, I'm on OSx and I'm experiencing this bug as well.

```
Version: 1.47.0-insider
Commit: 0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69
Date: 2020-06-23T09:38:28.751Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.5.0
```

**Comment by mhutchie** [comment] 2020-06-30 12:42
@LongLiveCHIEF It looks like the version of Visual Studio Code Insiders you have (2020-06-23) is one of the releases with the bug, upgrading to the latest Visual Studio Code Insiders release should fix it for you.

**Comment by volopasse** [comment] 2020-07-02 15:26
Seems to be fixed in [e96aaa0](https://github.com/microsoft/vscode/commit/e96aaa0befaabe39a4579081a6fa5e75c5e838b8), can see it working in the latest release

```
Version: 1.47.0-insider (user setup)
Commit: 04545fa88043fd10d1f3edefd26be1b8245b516f
Date: 2020-07-02T05:48:37.715Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by JustinGrote** [comment] 2020-07-02 15:46
Has stayed fixed for me for a couple days now.

**Comment by mfmayer** [comment] 2020-11-17 07:24
I'm still observing this, especially after sleep/hibernate. In such case gitgraph must be closed and reopened. That's a pitty because otherwise I would pin gitgraph tab in VSCode.

```
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by mhutchie** [comment] 2020-11-17 07:48
Hi @mfmayer,

For the most part this issue has seemed to be resolved by the Visual Studio Code team for the last few months. Only a handful of users have continued observe this Visual Studio Code issue, and the common cause to all of them is that they're using WSL2. Are you using WSL2?
* If so, I think there's probably still an open issue in [vscode](https://github.com/microsoft/vscode) for it.
* If not, please raise it as a bug in [vscode](https://github.com/microsoft/vscode) - if another Visual Studio Code bug has been introduced, it's important to make sure the vscode team is aware of it, as this issue affects all extensions that use Webviews.

**Comment by ivancuric** [comment] 2020-12-24 12:12
Still observing this issue, using WSL2.

**Comment by tritemio** [comment] 2021-05-12 12:17
I am experiencing this issue with (I believe) the latest released vs code, on linux:

```
Version: 1.56.1
Commit: e713fe9b05fc24facbec8f34fb1017133858842b
Date: 2021-05-06T10:08:16.954Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-50-generic snap
```
