### ISSUE TITLE
Support for svn remote branches

### ISSUE THREAD

**Issue by randyou** [mhutchie/vscode-git-graph#107] opened 2019-06-19 08:37 UTC
**Describe the feature that you'd like**
I use git-svn , it can't show remote branches at version 1.8.0.  It worked well at old version. 

version:1.8.0
vscode version:1.35.1

**Comment by mhutchie** [comment] 2019-06-19 09:29
Hi,

Can you please try the following steps to double check this issue was introduced in 1.8.0:
1. Install the previous version (1.7.0)
2. Confirm the issue is not present in 1.7.0.
3. Install the current version (1.8.0)
4. Confirm that issue is present in 1.8.0.

To install another version of Git Graph: From the Visual Studio Code Extension menu, click on the "Manage" cog and select "Install Another Version..."

There were no changes to the handling of remotes in 1.8.0, so I doubt this has been introduced in it.

Can you please provide the following information so I can replicate your situation:
- What is working? (e.g. are all commits & branches visible)
- What is not working? (e.g. is it just the remote branch labels that are hidden, is the push branch / tag options visible on the respective context menus, is the "Fetch from Remote(s)" button visible)
- Is there anything unusual / uncommon about your repo / setup? (no one else using git-svn has reported any issues with remotes in the last 12 days since the update - I would have expected this to have been raised sooner if it was a bug in the release).
- A screenshot of the Git Graph top control bar, like:
![image](https://user-images.githubusercontent.com/5315753/59753533-aec7fd00-92c7-11e9-81d9-c309333a76a5.png)

**Comment by randyou** [comment] 2019-06-19 10:08
I found it works well at version 1.6.0 , 1.7.0 and 1.8.0 not works well.

works at 1.6.0 , it show "origin/trunk"
[works at 1.6.0](https://github.com/randyou/imgs/raw/master/1.png)
works at 7.7.0+, it not show "origin/trunk"
[works at 1.7.0+](https://github.com/randyou/imgs/raw/master/2.png)

**Comment by mhutchie** [comment] 2019-06-19 11:20
In 1.7.0 (released over three weeks ago), the detection of remotes was changed to use the result of `git remote`, instead of just implicitly resolving it from the remote branch ref names. This is required for the new functionality introduced in 1.7.0, specifically for better dealing with remotes (multiple remotes, and remotes with slashes in their name). (It's not a bug, it was intentionally changed)

Unfortunately it appears that `git remote` doesn't return svn remotes, as they aren't actually git remotes. It also appears that there isn't an equivalent way to get svn "remotes".

I'll adjust the new implementation of remote handling in the next release, so remote branches are still shown, even if the remote it is based on isn't returned by `git remote`.

**Comment by randyou** [comment] 2019-06-19 14:08
Thank you !

**Comment by mhutchie** [comment] 2019-06-21 06:13
This will be available in v1.9.0, which will be released in the next day.

**Closed by mhutchie** 2019-06-21 06:13 UTC
Labels: improvement
