### ISSUE TITLE
Include built-in support for several new emoji shortcodes recently added to gitmoji

### ISSUE THREAD

**Issue by TobiasTao** [mhutchie/vscode-git-graph#316] opened 2020-06-01 02:14 UTC
**Describe the Bug**
emoji `wastebasket` is not displayed correctly
![image](https://user-images.githubusercontent.com/37654563/83369384-bd32fa00-a3ee-11ea-89c8-28224b0e7b09.png)

**Expected Behaviour**
show： 🗑️ 
**Environment**
 - Git Graph Extension Version: [1.23.0]
 - Visual Studio Code Version: [1.45.1]
 - Operating System: [Windows 10]

**Comment by mhutchie** [comment] 2020-06-01 12:05
Hi @TobiasTao,

Git Graph has built-in support for many emoji shortcodes, including all of [gitmoji](https://gitmoji.carloscuesta.me/) and some other common shortcodes. As there are almost endless shortcodes and different flavours used around the world, I had to decide on a built-in set of the most common (`:wastebasket:` isn't one of them).

However, when I implemented emoji shortcode replacement, I also created a new Extension Setting [Custom Emoji Shortcode Mappings](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings#custom-emoji-shortcode-mappings) that allows users (like yourself) to define any other emoji's they use (that aren't built-in).

You will be able to use the above mentioned Extension Setting to define a custom mapping for `:wastebasket:` to your desired emoji.

I'll close this issue as it is not a bug, and this functionality is already provided in Git Graph.

**Comment by TobiasTao** [comment] 2020-06-02 12:45
Thanks you for your reply @mhutchie, but gitmoji already contains `:wastebasket:`
![image](https://user-images.githubusercontent.com/37654563/83521200-7ab60e00-a511-11ea-86aa-1a77f87f694e.png)
maybe you should update.

**Comment by mhutchie** [comment] 2020-06-02 21:10
Hi @TobiasTao,

Thanks for making me aware of that. Since Gitmoji has recently added `:wastebasket:` (after I added Gitmoji support), I’ll update the built-in list in Git Graph to include it and any other new emojis they’ve recently added.

**Comment by mhutchie** [comment] 2020-06-04 11:16
This will be available in v1.24.0.

If you'd like to use it before the next release, you can download [v1.24.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.24.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Closed by mhutchie** 2020-06-04 11:16 UTC
Labels: improvement

**Comment by ADIX7** [comment] 2020-11-02 08:39
@mhutchie On https://gitmoji.carloscuesta.me/ the documentation icon is now ```:memo:``` while in your extension it is ```:pencil:```. Has it been renamed on the site?

**Comment by mhutchie** [comment] 2020-11-02 09:09
Hi @ADIX7,

I've just compared the set of short-codes I last imported from gitmoji into Git Graph, to the latest set of gitmoji. In the last five months, gitmoji have made the following changes:
* Renamed `:pencil:` to `:memo:`
* Added `:hammer:`
* Added `:passport-control:`

I'll apply these changes in the next release of Git Graph, and reply to this thread with a link to a beta release with these changes within the next week.

I've include importing gitmoji into my pre-release steps, so that going forward the set of gitmoji in Git Graph is always kept in sync.

**Comment by ADIX7** [comment] 2020-11-02 09:10
Sounds great, thank you for the fast response!

**Comment by mhutchie** [comment] 2020-11-07 04:18
Hi @ADIX7,

The delivery of the built-in support for the new Gitmoji was tracked by #409. Please see my closure comment on it for a link to the beta release, and instructions for how to install it.
