### ISSUE TITLE
Unable To Load Repository Settings

### ISSUE THREAD

**Issue by rchavezj** [mhutchie/vscode-git-graph#345] opened 2020-07-13 23:35 UTC
![gitconfig](https://user-images.githubusercontent.com/10482151/87363702-93f5a580-c526-11ea-833d-783c5e4232de.png)

Recently on git graph, every time I click on it's setting icon, I get an error saying I am unable to load the repository settings. Need help :(

**Comment by mhutchie** [comment] 2020-07-14 08:27
Hi @rchavezj,

Git Graph runs these three standard Git commands from the repositories root directory when loading the Repository Settings Widget:
1. `git --no-pager config --list --local`
2. `git --no-pager config --list --global`
3. `git remote`

If you open a Visual Studio Code Terminal to the root directory of the repository, and try running each of these commands, you should be able to observe one of them returning the same Git error that Git Graph is passing on to you in the UI. (I'm guessing it would most likely be thrown by the second command).

Once you've identified the Git command causing the problem, you should then be able to do a quick Google search to identify steps to resolve this underlying Git configuration issue on your computer.

I'll close this question as it appears to most likely be caused by a local Git configuration issue on your computer (Git Graph is just passing on the Git error message to you). I'll still receive notifications of any replies you make, so we can continue to discuss further troubleshooting steps if necessary.

**Closed by mhutchie** 2020-07-14 08:27 UTC
Labels: question

**Comment by rchavezj** [comment] 2020-07-14 16:11
I get the same error when executing the 2nd command:

git --no-pager config --list --global 

I fixed the issue after setting up my email and name

git config --global user.name
git config --global user.email

I appreciate the assistance! Love your work on git graph
