### ISSUE TITLE
Git executable not found when project have repository in subfolder

### ISSUE THREAD

**Issue by scippio** [mhutchie/vscode-git-graph#66] opened 2019-05-09 08:49 UTC
**Describe the bug**
Git executable not found when project have repository in subfolder

**What does the bug relate to**
All

**To reproduce**
Steps to reproduce the behaviour:
1. open project wiht .git repo in subfolder
2. run git graph

**Environment**
 - OS: Archlinux - Linux x64 5.0.12-arch2-1-ARCH
 - Visual Studio Code Version: 1.34.0-insider

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/672903/57440246-f595f200-7247-11e9-83ca-ee3e72e9fe4f.png)

**Comment by mhutchie** [comment] 2019-05-09 09:31
To enable detection of repositories in subfolders, you must set the extension setting `git-graph.maxDepthOfRepoSearch` to a suitable depth, as described in the [Extension Settings](https://github.com/mhutchie/vscode-git-graph/wiki/Extension-Settings) documentation.

Please close this issue if the above information resolves this issue. If not, please let me know so we can troubleshoot further.

**Comment by mhutchie** [comment] 2019-05-10 11:34
I’m closing this issue as it is most likely caused by your Git Graph settings as described above. If you still have difficulty getting it to work, please reply and we can troubleshoot further.

**Closed by mhutchie** 2019-05-10 11:34 UTC
