### ISSUE TITLE
Git state doesn't update after switching branches

### ISSUE THREAD

**Issue by mindplay-dk** [mhutchie/vscode-git-graph#280] opened 2020-03-20 09:22 UTC
This issue is most easily explained with a GIF.

Here I'm switching from master to another branch, and the Git UI doesn't update:

![git-desync](https://user-images.githubusercontent.com/103348/77150441-2fed3400-6a94-11ea-9ba0-22dcbb863f6b.gif)

Not sure if this is a bug in VS Code or Git Graph. :thinking: 

**Environment**
 - Git Graph Extension Version: 1.21.0
 - Visual Studio Code Version: 1.43.1
 - Operating System: Ubuntu 19.10

**Comment by mhutchie** [comment] 2020-03-20 09:51
I previously responded to an identical issue #275.

When you checkout `ip-detection`, after the "Checking out branch..." dialog closes the branch label is bolded and it has a colour outline. Because it is bolded, that indicates that the branch was checked out by Git, and when the Git Graph View automatically refreshed, Git confirmed the branch was successfully checked out. This indicates that Git Graph is functioning completely as expected, the branch was checked out in the repository immediately when you ran the action.

The delay in the branch being indicated by Visual Studio Code as checked out is due to how Visual Studio Code is monitoring the File System for events within the repository. Visual Studio Code uses these events to do a background refresh, and update the branch it indicates as currently checked out. File System event monitoring in Visual Studio Code is notoriously unpredictable (there are many factors that can influence it).

Visual Studio Code's monitoring of the repository (and consequent updates to their Git UI & Status Bar Item) is completely unrelated to Git Graph. There also isn't anything I can do in Git Graph to make Visual Studio Code refresh more consistently / faster after the repository changes (e.g. after a branch is checked out).

FYI: You should be able to observe the same delayed updates of Visual Studio Code's Git UI & Status Bar item if you run the Git command `git checkout ip-detection` in a terminal window. _(this is all that Git Graph is doing when you run the checkout branch action)_

I'll close this issue as it is unrelated to Git Graph, and I'm unable to make any changes that would make Visual Studio Code update any faster.

**Closed by mhutchie** 2020-03-20 09:51 UTC
Labels: bug
