### ISSUE TITLE
Fix modal close on push branch

### ISSUE THREAD

**Issue by rbalet** [mhutchie/vscode-git-graph#148] opened 2019-07-30 06:41 UTC
**Describe the bug**
The git graph modal are automatically closing on refresh

**What does the bug relate to**
- Running a Git Command
- Graph Refresh

**To reproduce**
1. Pushing branch with the native vs code push button (ex to master)
2. Right click on a branch (master) 
3. Add a Tag...
4. Type the new tag you want

When the pushing get finish, the modal closes automatically.

**Expected behaviour**
The modal should stay open

**Environment**
 - Windows 10
 - Visual Studio Code Version: 1.36.1

**Comment by mhutchie** [comment] 2019-07-30 08:34
This is the expected behaviour as when a refresh occurs, there is no guarantee that the commit / branch / tag that the dialog was opened for still exists and has the same state. If the dialog wasn't closed by Git Graph, then the user could attempt to run a git command that could have a completely different behaviour if the git state has changed (e.g. rebasing).

The extension does currently check to see if the commits, branches and tags are all the same and haven't changed position, in which case the opened dialog will stay open. It is only because in your example you're pushing a branch, and the remote branch ref changed location, that it is unable to determine that this change didn't have an effect that would impact the opened dialog, so it will close it.

I'm closing this issue, as it is the expected behaviour, and there no more effective (and feasible) way of determining the influence of a an arbitrary change during a refresh on the validity of the open dialog.

Please let me know if you have a method that will work for all of the dialogs in Git Graph, then I'd be happy to implement it.

**Closed by mhutchie** 2019-07-30 08:34 UTC
Labels: bug

**Comment by rbalet** [comment] 2019-11-29 08:21
Hi, I had have an Idea and wanted to share it with you.
We could implement in every line an observable which will emit a status when the line is changing (`change`, `delete`, `...`).
With it, when we click on a line (ex: right click -> Add Tag..) we could subscribe the next box to the observable of the line. When subscribe receive a `delete` or any state that may interfer with the good working of the app, we will autoclose the dialog. If not, we will keep it open.
What do you think of that (It's juste an idea :)

**Comment by mhutchie** [comment] 2019-11-29 09:03
Thanks for the idea! I’ll have a look into it as it’s not an approach I’ve used before, however is definitely worth considering (as it could be a very clean way to approach the task).

Throughout some of the last releases I’ve been making behind the scenes changes to how dialogs are implemented in the Git Graph UI. This has been done with the following end goals in mind:
* Keeping dialogs open if their commit hasn’t been affected during a refresh.
* Allowing multiple dialogs to be open simultaneously (instead of one at a time).

I’ll keep you updated with my progress on these!
