### ISSUE TITLE
Add --allow-unrelated-histories possibility for merge or pull

### ISSUE THREAD

**Issue by AlexVillarra** [mhutchie/vscode-git-graph#425] opened 2020-12-02 17:59 UTC
Hello, I was wondering if it's possible to add an option to be able to use "--allow-unrelated-histories" in git merge or git pull. I know it is not a mayor improvement but I think it should be possible without too much hassle.

**Comment by mhutchie** [comment] 2020-12-02 20:15
Hi @AlexVillarra,

Thank you for raising this improvement request!

It would definitely be easy to add this option to the merge and pull dialogs, however after reading what the option enables, I’m currently not convinced it’s right thing to do, as:
* I expect this option would only be used extremely infrequently. This seems to be confirmed by the Git docs mentioning it’s “a very rare occasion”.
* Currently the merge dialog already has three checkboxes, and the pull dialog already has two checkboxes. Even having the current number of checkboxes is intimidating and slightly confusing to some newer users (based on the feedback I’ve received), so I need to be careful not to overload them even more by adding too many other options (especially if they’re rarely used, and their meaning / usage isn’t completely obvious to users who haven’t seen it before).

I’ll leave this request open for a while to get feedback from the user community around how frequently this option would be used in day-to-day work. Please let me know if it has broader use cases than what is mentioned in the Git docs, as the infrequency of its usage is the main reason I’m not convinced it should be added.

FYI: This consideration applies to all Git commands, there are usually heaps of options for each of them. It’s not a good user experience to provide all of them to the user in a UI, imagine how confusing it would be if a dialog had 10+ checkboxes and drop downs. It’s critical for me to ensure that every option added to a dialog is used frequently enough by a decent portion of users, such that it adds more value than all of the drawbacks to the users who will likely never use it.

**Comment by AlexVillarra** [comment] 2020-12-03 07:51
Wow that was a quick reply =) . Indeed it is an option that would be seldom used, and I had not thought about how it might saturate the UI, or how it might lead to confusion. I agree that maybe it should only be implemented if requested by more users (which seems unlikely).
Thanks again for the quick response, and in the future I'll have this in mind if I ever come on an idea of a feature or improvement.

**Comment by mhutchie** [comment] 2020-12-06 10:31
I'll close this improvement request for now and move it to the backlog, as all indications so far suggest that it wouldn't be used frequently enough to justify it's inclusion on the Merge & Pull Dialogs, and outweigh the various negatives I previously mentioned.

Note to users reading this in the future: If you'd like this functionality, please reply to this thread to express your interest. I'd happily re-consider this feature if there was enough of an indication that it would be used by a decent number of users.

**Closed by mhutchie** 2020-12-06 10:31 UTC
Labels: backlog, improvement

**Comment by zamirD123** [comment] 2023-08-16 09:02
Almost three years later haha, but I would like to have the option

**Comment by curiosbasant** [comment] 2024-06-14 06:14
Yes, I also need this functionality. Maybe you can give settings to enable checkboxes that the user wants in the UI.
