### ISSUE TITLE
Support for `--recurse-submodules` in right-click context menu

### ISSUE THREAD

**Issue by ahwitz** [mhutchie/vscode-git-graph#526] opened 2021-06-15 15:52 UTC
**Describe the feature that you'd like**
We have a repo with a submodule in it, and every time we use the right-click "Checkout branch..." option, it shows up with the submodule as being modified in the base VS Code source control pane because the module hasn't been updated. Using the `--recurse-submodules` flag with `git checkout` doesn't have that happen, but I don't see an option to add that flag when checking out a branch in a repository with submodules. Can one be added?

**Additional context (optional)**
Don't think anything else is needed? Thanks for anything you can do!

**Comment by mhutchie** [comment] 2021-06-15 21:23
Duplicate of #352 - Please read my previous responses.

FYI: According to https://git-scm.com/book/en/v2/Git-Tools-Submodules, running `git config submodule.recurse true` may achieve what you’re wanting as a work-around.

**Closed as completed by mhutchie** 2021-06-15 21:23 UTC
Labels: duplicate

**Comment by ahwitz** [comment] 2021-06-15 21:26
Perfect, thanks! Searched "recurse" and didn't see any results, so sorry for the dupe!
