### ISSUE TITLE
Git Graph broken as of VS Code 1.52?

### ISSUE THREAD

**Issue by robvitaro** [mhutchie/vscode-git-graph#436] opened 2020-12-14 16:27 UTC
**Describe the Bug**
As of VSCode 1.52 I cannot display GitGraph

**Steps to Reproduce**
1. Click "Git Graph" button on the status bar at the bottom of the application
2. See screenshot below

**Expected Behavior**
I expect to see the graph

**Environment**
 - Git Graph Extension Version: 1.28
 - Visual Studio Code Version: 1.52
 - Operating System: Windows 10

VS Code details
Version: 1.52.0 (user setup)
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Screenshots (optional)**

![image](https://user-images.githubusercontent.com/19912174/102106706-e5b89980-3dfe-11eb-8d8b-cd94c2bccd80.png)

**Comment by mhutchie** [comment] 2020-12-14 20:04
Hi @robvitaro,

I've had no other reports of this occurring for any other users after upgrading to Visual Studio Code 1.52.0. After every release I always also check the extension myself on multiple operating systems (I didn't notice anything either).

This behaviour occurs when Visual Studio Code fails to load the CSS & JS resources packaged in the extension that the Git Graph View requires. If you run the "Developer: Open Webview Developer Tools" command from the Visual Studio Code Command Palette, and switch to the Console Tab, you'll be able to see the errors that Visual Studio Code is having. These error logs will tell you to path of the two required files `out.min.js` and `out.min.css`.

There are two possible causes of the behaviour you've observed:
1. In rare cases it's possible that Visual Studio Code incorrectly unpacks the extension when it was last installed, or for some reason some of the extensions files on disk were deleted. To check if this is the case, check your file system for the files I mentioned above in the error logs. If they do not exist, you just need install a previous version of Git Graph, and then update back to the latest version to restore these files.
2. This is caused by a Visual Studio Code bug with their [Webview](https://code.visualstudio.com/api/extension-guides/webview) implementation, that affects all extensions that use Webview's (not just Git Graph). Unfortunately there have been numerous of these Visual Studio Code Webview bugs this year (many are related to the compatibility with WSL #378 - this one https://github.com/microsoft/vscode/issues/105536 is still open). Please follow it for Microsoft's resolution of this issue, or raise a new bug with Microsoft if `out.min.js` and `out.min.css` are on you computer in the correct location, but Visual Studio Code is failing to provide them in the Git Graph View's Webview. Visual Studio Code is responsible for creating Webview's for extensions, and providing the resources that the extensions require (they don't allow any other method).

I'll close this issue as either:
* You just need to follow the steps I mentioned in (1), and there is nothing I can do about these files not existing on your computer (the extension definitely has no way of deleting them).
* It is a Visual Studio Code bug, and either this is the same as the issue that's already being tracked by Microsoft, or you should open a new issue in their repo (e.g. "Unable to load Webview's resources").

**Closed by mhutchie** 2020-12-14 20:04 UTC
Labels: vscode-bug

**Comment by robvitaro** [comment] 2020-12-14 20:28
@mhutchie, I appreciate you taking the time to give such a detailed response. Looks as if my problem is 2, as I use WSL 2. I used one of the commenters' suggestion of starting WSL before opening VS Code, that is an acceptable workaround. Thanks so much.

**Comment by mhutchie** [comment] 2020-12-14 20:34
Hi @robvitaro,

Thanks for letting me know that this is WSL2 related! I'm glad you have an acceptable workaround until it is properly fixed.
