### ISSUE TITLE
Git Graph doesn't work anymore with vscode 1.42

### ISSUE THREAD

**Issue by wimille** [mhutchie/vscode-git-graph#261] opened 2020-02-18 08:26 UTC
Hi,

I don't know if it is a bug or a wrong configuration on my computer but i've an issue with git-graph and the lastest version of vscode.
Here's the things i've done:
1. Open vscode
2. Drag'n Drop a local file which is in a directory under git control.
3. On source control tab, i saw that my file appears as modified (expected because i don't commit it yet)
4. Click on "view git graph" button

Then i've the following error:
````
Unable to load Git Graph
No Git repositories were found in the current workspace when it was last scanned by Git Graph.

If your repositories are in subfolders of the open workspace folder(s), make sure you have set the Git Graph Setting "git-graph.maxDepthOfRepoSearch" appropriately (read the documentation for more information).
````

If i made exactly the same test with vscode 1.41.1, all works fine, and i can see the graph.

Can you help me  to understand what happens?

Regards
Mathieu

**Comment by mhutchie** [comment] 2020-02-18 10:23
Hi Mathieu,

No one else has reported any compatibility issues with Visual Studio Code 1.42.x which has been available for 13 days, so I don't expect this to be a problem with Git Graph, it's almost certainly something specific to your computer.

Based on the information you've provided, I've followed the steps and I only get the expected behaviour in vscode 1.42.1.

Please provide the following information:
* I'd suggest you look at the Git Graph Output Channel in the Visual Studio Code Output Panel to see if there are any errors or unexpected log messages. Please copy the Output Channel contents in a reply to this thread, so I can spot what might be causing your issue.
* Also include the Output Channel contents after "Re-scan the current workspace for repositories" button is pressed.
* What Git Graph & Operating System versions are you using?
* Are you getting this behaviour for all of your repositories, or just under the specific scenario you described?
* Is there anything unusual about the specific repository (e.g. symlinks etc.)?

I'll close this issue for now as if there was a compatibility issue with Git Graph in vscode 1.42.x, at least one of the other 160,000+ active daily users of the extension would have observed it in the last 13 days. We'll still troubleshoot your issue in this thread (it just saves the noise for others with active feature requests etc.). In the unlikely event a code change is required, I'll reopen and implement it under this issue.

**Closed by mhutchie** 2020-02-18 10:23 UTC

**Comment by wimille** [comment] 2020-02-18 10:51
Hi,

Thank you for your feedback. I'm okay with your comment, i think it is a problem with my computer.

For information:
1. I use vscode standard (eg. not the insiders version) with git graph 1.21.0 on Windows 10.
2. There is no specific messages on output channel:
```
[2020-02-18 11:49:31.006] Searching workspace for new repos ...
[2020-02-18 11:49:31.006] Completed searching workspace for new repos
```
3. Yes, i have the same behavior on every GIT repository i have.
4. No, it is a basic GIT repos (no link) all files are on the same drive and the same repository.

**Comment by mhutchie** [comment] 2020-02-18 11:17
Can you please include the entire Output Channel content, from start up through to opening the view and pressing the re-scan button?

**Comment by wimille** [comment] 2020-02-18 17:56
Hi,

1. here the output channel for git graph
```
[2020-02-18 18:52:01.262] Starting Git Graph ...
[2020-02-18 18:52:01.847] Using C:\Program Files\Git\bin\git.exe (version: 2.25.0.windows.1)
[2020-02-18 18:52:01.857] Started Git Graph - Ready to use!
[2020-02-18 18:52:01.857] Searching workspace for new repos ...
[2020-02-18 18:52:01.857] Completed searching workspace for new repos
[2020-02-18 18:52:46.386] Created Git Graph View
[2020-02-18 18:52:49.202] Searching workspace for new repos ...
[2020-02-18 18:52:49.202] Completed searching workspace for new repos
```

2. Value is defined to 4

3. The structure is:
```
repo1
    file4
    subfolder1
        file1
    subfolder2
        file2
        file3
```
Whatever the file i tried to open, i have the same behavior.

**Comment by mhutchie** [comment] 2020-02-19 09:11
I've tested the extension using your exact environment (Windows 10, Visual Studio Code 1.42.1, Git 2.25.0.windows.1, Git Graph 1.21.0) and haven't been able to replicate the behaviour you're observing at all.

For reference, the Output Channel I get (demonstrating the correct behaviour) is included below. It shows the normal behaviour when opening a new repo for the first time, where the top level repo is checked and then added.
```
[2020-02-19 19:45:40.846] Starting Git Graph ...
[2020-02-19 19:45:40.959] Using C:\Program Files\Git\cmd\git.exe (version: 2.25.0.windows.1)
[2020-02-19 19:45:40.961] Started Git Graph - Ready to use!
[2020-02-19 19:45:40.961] Searching workspace for new repos ...
[2020-02-19 19:45:40.967] > git rev-parse --show-toplevel
[2020-02-19 19:45:41.058] Added new repo: c:/Users/Michael/Dev/vscode-git-graph-examples/repo1
[2020-02-19 19:45:41.059] Completed searching workspace for new repos
[2020-02-19 19:45:44.065] Created Git Graph View
[2020-02-19 19:45:44.415] > git branch -a --no-color
[2020-02-19 19:45:44.421] > git remote
[2020-02-19 19:45:44.486] Started watching repo: c:/Users/Michael/Dev/vscode-git-graph-examples/repo1
[2020-02-19 19:45:44.505] > git log --max-count=301 --format=... --date-order --branches --tags --remotes HEAD --
[2020-02-19 19:45:44.514] > git show-ref -d --head
[2020-02-19 19:45:44.519] > git reflog --format=... refs/stash --
[2020-02-19 19:45:44.594] > git status -s --branch --untracked-files --porcelain
```

I see that in your output the extension isn't testing if any directories are git repositories (by running `git rev-parse --show-toplevel`) between `Searching workspace for new repos ...` and `Completed searching workspace for new repos`.

Please include the JSON of the "Max Depth Of Repo Search" extension setting, e.g. `"git-graph.maxDepthOfRepoSearch": 3` to confirm it is being set correctly.

Please provide a concrete example with an exact set of unambiguous steps that demonstrate the behaviour you're observing in a new git repository that hasn't been opened in Visual Studio Code (this is so I can replicated it exactly). In addition to the steps, please include:
* The structure of the repo. Indicate the workspace root / folder that is opened in Visual Studio Code (like in the example I provided in my previous comment), not just the structure.
* Specify which file you are "dragging and dropping".
* List the name(s) of the repository(ies) in the Visual Studio Code Source Control View.
* As much detail as possible so there is absolutely no room for misinterpretation. For example, explain exactly what you mean by "Drag'n Drop a local file which is in a directory under git control." by breaking it down into multiple steps (e.g. clearly indicating where you are dragging from and to).

**Comment by wimille** [comment] 2020-02-23 16:59
Hi,
i've some new test today.
I've re-install vscode 1.42.1, and git-graph. I've also deleted the vscode repository from %appdata%. So i've starded without any personnal settings.
And i use on of my own github repository (https://github.com/wimille/Ultraedit)

I've opened the readme.md file, it is correctly seen as a versionned file in the souce version tab. But when i try to launch the git-graph tool, i've the same result (no git repository is detected).

**Comment by wimille** [comment] 2020-02-25 09:33
Hi,
I had the possibility to make the test on a fresh installed PC. i've installed Git for windows, vscode 1.42. (user install) and git graph.
I use the previous github repository. Same issue, git-graph shows nothing.

**Comment by mhutchie** [comment] 2020-02-25 10:19
Please provide all of the information I requested in my previous response so I can attempt to identify what is causing the behaviour you're observing:

>Please include the JSON of the "Max Depth Of Repo Search" extension setting, e.g. `"git-graph.maxDepthOfRepoSearch": 3` to confirm it is being set correctly.
>
>Please provide a concrete example with an exact set of unambiguous steps that demonstrate the behaviour you're observing in a new git repository that hasn't been opened in Visual Studio Code. Hopefully this should enable me to replicate your actions exactly. In addition to the steps, please include:
>* The structure of the repo. Indicate the workspace root / folder that is opened in Visual Studio Code (like in the example I provided in my previous comment), not just the structure. A screenshot of the Visual Studio Code Explorer View with all folders expanded would be useful for this.
>* Specify which file you are "dragging and dropping".
>* List the name(s) of the repository(ies) in the Visual Studio Code Source Control View.
>* As much detail as possible so there is absolutely no room for misinterpretation. For example, explain exactly what you mean by "Drag'n Drop a local file which is in a directory under git control." by breaking it down into multiple steps (e.g. clearly indicating where you are dragging from and to).

**Comment by wimille** [comment] 2020-02-25 13:54
Hi,

The operation i made are very very simple:
1. Open vscode form installation directory
    Vscode is empty.
2. From explorer drag and drop file into vscode
3. Check into source control tab and launch git graph

I don't clearly understood what you mean by "Indicate the workspace root / folder that is opened in Visual Studio" ? 
However, i made a new try, i open a folder (which is a git repository) in vscode and then git-graph works fine!

**Comment by mhutchie** [comment] 2020-03-03 10:54
The workspace root / folders are the folders that are open in the Visual Studio Code Workspace. For example, when you open the "Ultraedit" folder in Visual Studio Code (using File > Open Folder), "Ultraedit" is the workspace root.
Based on the information you provided in your previous response (indicating Visual Studio Code is empty when it is open), the workspace won't contain any root or folders. The screenshot below indicates what I believe you are seeing (see "Explorer: No Folder Opened"):

![image](https://user-images.githubusercontent.com/5315753/75761177-ba435180-5d8c-11ea-95f9-08bef90fe382.png)

Git Graph searches for repositories recursively through the workspace root / folders, while respecting `git-graph.maxDepthOfRepoSearch`. As you don't have a workspace root / folders, Git Graph doesn't have any folders to search (and hence it doesn't detect any repositories). This is confirmed from the log output you previously provided:
```
[2020-02-18 18:52:01.857] Searching workspace for new repos ...
[2020-02-18 18:52:01.857] Completed searching workspace for new repos
```

I found that I had to reset `git.autoRepositoryDetection` back to the default value, for the Visual Studio Code Source Control View to detect the repository based on the subfolders *and* open editors. I had configured this setting to `false` a while back to test something else with the extension (this prevented me from being able to replicate your third step in your first comment `3. On source control tab, i saw that my file appears as modified`). Now I can observe the screenshot below, that indicates the "Ultraedit" repository open in the Visual Studio Code Source Control View, and contains a modification:
![image](https://user-images.githubusercontent.com/5315753/75763415-56bb2300-5d90-11ea-9a82-e1a73790ad07.png)

At this stage, when I run the "Git Graph: View Git Graph" command in the Visual Studio Code Command Palette, I get the message you mentioned (as expected because only Visual Studio Code knows about the repository, not Git Graph).
![image](https://user-images.githubusercontent.com/5315753/75768201-021ba600-5d98-11ea-9a80-3c2918e391b0.png)

You can force the repository to be opened in the Git Graph View from the Source Control button (see screenshot below). The "Git Graph" Status Bar item also appears as the repository is now known to Git Graph. The repository will stay available in Git Graph until Visual Studio Code is restarted, because as soon as Visual Studio Code is started Git Graph will remove the repository as it is not in the workspace.
![image](https://user-images.githubusercontent.com/5315753/75763958-3fc90080-5d91-11ea-9892-de4f03a9043e.png)

Please respond with contradicting screenshots if you don't observe the screenshots I've provided.

---

What I still don't understand is that I don't see any change in behaviour in Visual Studio Code 1.42 (from what I can see this behaviour has always existed). It is exactly what I always expected to happen.

Git Graph currently requires that repositories are within the workspace root / folders as it is necessary for various behind-the-scenes functions, such as detecting file system events within the repository for automatic background refreshing (among many other things).

While it is definitely possible for me to implement changes so that Git Graph matches Visual Studio Code's `git.autoRepositoryDetection = true || openEditors` behaviour, I believe that the current workspace restrictions result in a better experience for users. If I was to implement such changes, it would have significant complexity and a cost to Visual Studio Code performance.

You are the first person (out of 310,000+ users) that has told me that they edit single files (instead of opening one or more folders to work within), and would benefit from this use case better integrating with Git Graph. I'll add a backlog label to this feature, so that if a number of other users also indicate they would like this, I can prioritise the implementation of these changes appropriately.

In the meantime, I'd appreciate & suggest that you see if you can modify your workflow to open the repository you're working in as a folder in Visual Studio Code. This is the standard use case of the extension used by almost all Git Graph users, is fully supported, and has many other user experience benefits.
