### ISSUE TITLE
Force some branches to display on the left side

### ISSUE THREAD

**Issue by urielzen** [mhutchie/vscode-git-graph#633] opened 2022-03-04 07:02 UTC
Currently the latest commit seems to be driving what branch is display on the left
![image](https://user-images.githubusercontent.com/7947179/156714517-43c13379-a1f4-4493-b838-76f9466888e2.png)

I would like if possible, have setting where I can override the default behavior and for some branches to be on the left in certain order.

For example, let's say that I would like `main` to be the first on the left, followed by `develop`, after those two the default behavior applies for the other branches.

something like this, regardless which branch has the latest commit.
![image](https://user-images.githubusercontent.com/7947179/156715213-dc0b7c5b-f6a1-43e0-8451-be11a23577bd.png)

**Comment by mhutchie** [comment] 2022-03-04 07:39
Duplicate of #207.

**Closed as completed by mhutchie** 2022-03-04 07:39 UTC
Labels: duplicate
