### ISSUE TITLE
Unable to load commits

### ISSUE THREAD

**Issue by atinyakov** [mhutchie/vscode-git-graph#450] opened 2021-01-14 12:01 UTC
**Describe the Bug**
Error: Unable to load commits
fatal: bad revision 'Head'

on any work directory I have

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Click on 'Git Graph' in VS Code pane
2. See error

**Expected Behaviour**
No error

**Environment**
 - Git Graph Extension Version: 1.28.0
 - Visual Studio Code: 1.52.1
 - Operating System: Windows 8.1

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/33699664/104587572-20b92180-5678-11eb-82aa-6d77d9aebae2.png)

**Comment by mhutchie** [comment] 2021-01-14 13:09
Hi @atinyakov,

When Git Graph is loading commits, it has to run the following three Git commands to get the commit information to display in the Git Graph View:
* `git log --max-count=301 --date-order --branches --tags --remotes HEAD --`
* `git show-ref -d --head`
* `git status --untracked-files=all --porcelain`

The error you're receiving is because one of these three Git commands is failing with the `fatal: bad revision 'HEAD'` error message (it is not an error in Git Graph itself). As one of these Git commands is failing, Git Graph is unable to get the required commit information, and is therefore unable to load the commits of your repository. These three Git commands are extremely common, and no other users have ever reported any problems with these Git commands (so the commands themselves are fine), one of them is just unable to be run in your repository.

I'd suggest for you to try running each of these three Git commands in one of the repositories you're receiving this error in, to work out which command is failing with `fatal: bad revision 'HEAD'`. Once you have identified the Git command, it should be relatively easy to find out why this is occurring and for you to fix it - there are heaps of Google search results to help correct this Git error.

Another thing for you to check is what version of Git that Git Graph is using on your computer - if it's very old I'd suggest you should update it. You can find out what version of Git that Git Graph is using by running the "Git Graph: Get Version Information" command in the Visual Studio Code Command Palette.

I'll close this as it is not a bug in Git Graph, it is an error being returned by Git in your repository. However, please reply to let me know how you go, or if you're unable to resolve it following the above steps - I'll provide any help I can to resolve this with you.

**Closed by mhutchie** 2021-01-14 13:09 UTC
Labels: question

**Comment by atinyakov** [comment] 2021-01-15 09:14
Thank you for responce,

I have executed all the provided commands, and it seems that there are no failures here, see:
![image](https://user-images.githubusercontent.com/33699664/104705364-de045180-572a-11eb-8e48-993f109361cd.png)

**Comment by mhutchie** [comment] 2021-01-15 10:18
Hi @atinyakov,

As long as the Git commands don't return `fatal: bad revision 'HEAD'`, then the command executed fine (blank responses are fine).

If you look at the Git Graph Output Channel in Visual Studio Code, you'll be able to see which version of Git the extension is using. For example, this is what the Output Channel looks like for me:

![image](https://user-images.githubusercontent.com/5315753/104711000-e6817a00-5774-11eb-826b-fd2cef8b1d09.png)

Please confirm that this is the same Git executable that you're using in the terminal. Some users in the past have unknowingly had multiple Git executables installed on their computer, with one having a problem. If the Git executable used by Git Graph is not the same as the one you're using in the terminal, you can set the following Visual Studio Code Setting to force a specific Git executable to be used by Visual Studio Code and Git Graph (so it matches what you're using in your terminal):
`"git.path": "C:\\Program Files\\Git\\cmd\\git.exe",`

I also noticed in your screenshot that it looks like you're running the Git commands via mingw64. Try running the Git commands I previously mentioned in the Windows Command Prompt, as Visual Studio Code and Git Graph invoke Git directly (not via mingw64), to see if it behaves any differently.

**Comment by atinyakov** [comment] 2021-01-15 10:42
Here is my output
![image](https://user-images.githubusercontent.com/33699664/104714412-37be4900-5736-11eb-9c49-944471e080e2.png)

I also not quire following your regarding mingw64. I am using Windows, so I had to install Git Bash, which I suppose is using mingw64?

PowerShell show the same result as bash
![image](https://user-images.githubusercontent.com/33699664/104715299-6be63980-5737-11eb-8e57-36576ad078b5.png)

**Comment by mhutchie** [comment] 2021-01-15 11:13
Which directory is the root of your repository `d:/htmlacademy/excel` or `d:/htmlacademy`?

Git Graph has detected that `d:/htmlacademy` is the root of the repository, so it is trying to run the Git commands in that directory. Git Graph detects the root of the repository by running the command `git rev-parse --show-toplevel`. Try running the three Git commands I previously mentioned in the same directory that Git Graph has identified as the repository root, to see if the error occurs.

You can manually add / remove repositories in Git Graph by running the `Git Graph: Add Git Repository` & `Git Graph: Remove Git Repository` commands in the Visual Studio Code Command Palette. If `d:/htmlacademy/excel` is the root of your repository, remove any existing repositories from Git Graph, and add it in. _(Although it will still only add in the root of the repository returned by running `git rev-parse --show-toplevel` in the selected directory)_
