### ISSUE TITLE
System keyboard shortcut to hide app does not work when git graph is frontmost.

### ISSUE THREAD

**Issue by mikebailey2** [mhutchie/vscode-git-graph#134] opened 2019-07-19 15:28 UTC
**Describe the bug**
On macOS when attempting to hide the current app via a keyboard shortcut (Cmd+H) if git graph is the frontmost tab then vscode will not hide. Switching to any other editor allows the keyboard shortcut to work.

I confirmed that there was not a conflicting keybinding set for the git graph extension.

**What does the bug relate to**
OS behavior

**To reproduce**
Steps to reproduce the behaviour:
1. Open a non-graph tab and use Cmd+H to verify the application will hide.
2. Go back into VS Code and open Git Graph tab.
3. Attempt to use Cmd+H again.

**Expected behaviour**
VSCode application hides in the backgroun.

**Environment**
 - OS: macOS 10.14.5
 - Visual Studio Code Version: 1.36.1

**Comment by mhutchie** [comment] 2019-07-20 00:13
The Git Graph extension doesn't block any keyboard shortcuts from the user being provided to Visual Studio Code.

This issue occurs when the users focus is in a [Visual Studio Code Webview](https://code.visualstudio.com/api/extension-guides/webview), for any extension that uses a Webview. For example, this issue also occurs with the [Edit csv](https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv) extension, because they are also using a Visual Studio Code Webview.

As this issue is caused by Visual Studio Code itself, not Git Graph, I'm closing this issue as there is nothing I can do within the extension to fix this issue. Please raise this issue in the [Microsoft/vscode](https://github.com/Microsoft/vscode) GitHub repo so Microsoft can investigate, fix & resolve this issue.

**Closed by mhutchie** 2019-07-20 00:13 UTC
Labels: bug

**Comment by mikebailey2** [comment] 2019-07-20 02:03
Thanks for the information about the real issue.
