### ISSUE TITLE
git graph can't display

### ISSUE THREAD

**Issue by LiXC-N** [mhutchie/vscode-git-graph#539] opened 2021-07-19 08:29 UTC
**Describe the Bug**
git graph can't display when I click the git graph on the status window.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1.click the git graph on the status window.

**Expected Behaviour**
show "Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.." Error

**Environment**
 - Git Graph Extension Version: 1.30.0
 - Visual Studio Code Version: 1.58.0
 - Operating System: ubuntu 20.04

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/31820839/126129608-46bbc568-cbae-4aab-b4ba-acc671d9a002.png)

**Additional Context (optional)**

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment] 2021-07-19 08:55
Duplicate of #524

**Closed as completed by mhutchie** 2021-07-19 08:55 UTC
Labels: vscode-bug
