### ISSUE TITLE
No graphical output at all under WSL, happens sporadically, solved by environmental restart

### ISSUE THREAD

**Issue by MrPointer** [mhutchie/vscode-git-graph#455] opened 2021-01-25 18:39 UTC
**Describe the Bug**
A picture is worth 1000 words, so please see the attached screenshot.  

As to when it happens - I honestly don't know! I can't seem to get a hold of any pattern, it happens quite randomly.  
When I restart WSL by issuing `wsl --shutdown` from Powershell, it usually solves the issue, but not always, sometimes several restarts are required. In the most severe case, I had to restart Windows entirely.  
Restarting vscode itself _does not help_!
This is the only vscode extension that has this kind of bug, and it appeared recently I'd say, during the last 2 months.

**Steps to Reproduce**
1. Open VSCode on Windows and use the WSL extension to connect to a WSL remote session
2. Click on the **git graph** status-bar button/label
3. Try and restart WSL using `wsl --shutdown` and repeat the steps until the issue is gone

**Expected Behaviour**
Extension always shows a graphical output 🙂 

**Environment**
 - Git Graph Extension Version: v1.28.0
 - Visual Studio Code Version: 1.52.1
 - Operating System: Windows 10 Pro ver 2004 build 19041.685 + WSL2 + Microsoft's Remote Extension

**Screenshots (optional)**
![git-graph-no-output](https://user-images.githubusercontent.com/10564482/105750205-1d157c80-5f4d-11eb-892f-8c65f3bb8ba3.png)

**Comment by mhutchie** [comment] 2021-01-25 21:42
Duplicate of #436.

Please see [my previous comment](https://github.com/mhutchie/vscode-git-graph/issues/436#issuecomment-744678297) for an explanation of what's occurring (you have cause 2) - this is a known Visual Studio Code WSL Webview bug, that affects all extensions that use Webview's (not just Git Graph).

**Closed by mhutchie** 2021-01-25 21:42 UTC
Labels: vscode-bug

**Comment by MrPointer** [comment] 2021-01-25 22:01
Oh sorry, couldn't find anything related to this bug while searching, I assumed it has something to do with WSL 😓 
Cheers mate! Thanks for the quick response 🙂
