### ISSUE TITLE
Version 1.27.0 doesn't work in WSL

### ISSUE THREAD

**Issue by sgaunet** [mhutchie/vscode-git-graph#418] opened 2020-11-18 06:40 UTC
**Describe the Bug**
Hello, git-graph 1.27.0 doesn't work in WSL, no error, but no graph too. There is just :

Repo:
Branches:
Show Remote Branches

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Open a workspace under WSL
2. Click on 'git-graph'
3. See no graph :(

**Expected Behaviour**
A beautiful graph :)

**Environment**
 - Git Graph Extension Version: 1.27.0
VSCode : 
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by mhutchie** [comment] 2020-11-18 07:22
Hi @sgaunet,

This behaviour occurs when Visual Studio Code fails to load the CSS & JS resources packaged in the extension that the Git Graph View requires. If you run the "Developer: Open Webview Developer Tools" command from the Visual Studio Code Command Palette, and switch to the Console Tab, you'll be able to see the errors that Visual Studio Code is having. These error logs will tell you to path of the two required files `out.min.js` and `out.min.css`.

There are two possible causes of the behaviour you've observed (the second is most likely):
1. If you just installed / updated the extension, in rare cases it's possible that Visual Studio Code incorrectly unpacked the extension. To check if this is the case, check your file system for the files I mentioned above in the error logs. If they do not exist, you just need install a previous version of Git Graph, and then update back to the latest version. If not, (2) must be what's occurring.
2. This is caused by a Visual Studio Code bug with their [Webview](https://code.visualstudio.com/api/extension-guides/webview) implementation's compatibility with WSL, that affects all extensions that use Webview's (not just Git Graph). There have been numerous of these Visual Studio Code Webview WSL bugs this year unfortunately, currently this one https://github.com/microsoft/vscode/issues/105536 is still open, so please follow it for Microsoft's resolution of this issue. This issue has been raised numerous other times in this repo, including #378.

I'll close this issue as either:
* You just need to follow the steps I mentioned in (1), and there is nothing I can do about Visual Studio Code failing to properly unpack the extension.
* It is a Visual Studio Code bug, and is already being tracked by Microsoft in their open issue.

**Closed by mhutchie** 2020-11-18 07:22 UTC
Labels: vscode-bug

**Comment by sgaunet** [comment] 2020-11-23 21:42
Sorry, the notification of your answer was in spam. Than you very much for your response.
