### ISSUE TITLE
Git Graph does not work properly in VS Code Insiders v1.47.0, but works great in VS Code v1.46.0.

### ISSUE THREAD

**Issue by LeonidRosin** [mhutchie/vscode-git-graph#333] opened 2020-06-25 13:18 UTC
Issue Type: <b>Bug</b>

Git Graph does not work properly in VS Code Insiders v1.46.1, but works great in VS Code v1.46.0.

Extension version: 1.24.0
VS Code version: Code - Insiders 1.47.0-insider (0913b1aa43191d8af0ccb4a133d9a8d7c1a81d69, 2020-06-23T09:03:35.861Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mhutchie** [comment] 2020-06-25 13:27
Closing as this is a duplicate of #317.

It is caused by a bug introduced by Microsoft in the latest Insiders build, that affects all extensions that use [Webview's](https://code.visualstudio.com/api/extension-guides/webview). As indicated by the linked issue, Microsoft has fixed the issue and it should be fixed in the next Insiders release.

**Closed by mhutchie** 2020-06-25 13:27 UTC
