### ISSUE TITLE
Commit Details View on merge commits shows files with diffs from all parents

### ISSUE THREAD

**Issue by alexeychikk** [mhutchie/vscode-git-graph#274] opened 2020-03-04 12:10 UTC
**Describe the Bug**
I had a lot of changes in my `develop` branch compared to the `master` branch. I had a conflict between `develop` and `master` so I decided to merge **`master` into `develop`**. There was only 1 file with conflict but your diff view in the merge commit **shows the complete difference between `master` and `develop`** however I didn't merge `develop` into `master`. There should be no visible changes except for that 1 conflict that I've fixed because **nothing has changed on the `develop` branch.** `Sublime Merge` shows the diff correctly

**Steps to Reproduce**
Please see the above.

**Expected Behaviour**
The extension should show correct commit diff.

**Environment**
 - Git Graph Extension Version: 1.21.0
 - Visual Studio Code Version: 1.42.1
 - Operating System: Ubuntu 18.04

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/10129207/75878182-dfce6a80-5e21-11ea-80a8-2c44b803ba80.png)

**Comment by mhutchie** [comment] 2020-03-04 21:16
The current behaviour was deliberately implemented for the reasons discussed below, it is not a bug (it’s just different to what you’re expecting).

Currently the Commit Details View shows the differences between the commit and its first parent (regardless of whether it is a commit, merge etc.). The benefit that this approach has, is when merging a (feature / bug) branch the merge commit’s Commit Detail View shows all of the changes that were merged from one branch into another (the entire feature / bug fix) with just a single click. This saves the user having to click through every commit on the branch to see all of the changes that occurred. This is generally quite useful, as if the approach you’ve described was taken, the Commit Details View of merge commits would not show any changes (if there were no conflicts), giving no useful information to the user. The approach I’ve taken was not something I just created or decided on myself, it’s also used by other Git UI’s such as SourceTree. It has also been accepted as the expected behaviour since I first published Git Graph over a year ago by 310,000+ users (you’re the first person to indicate they don’t like it).

In your use case I can definitely see the benefit of the behaviour you were expecting (and is available in SublimeMerge), so I’ll repurpose this issue into a feature request that would allow the user to choose their preferred behaviour through an extension setting.

**Comment by alexeychikk** [comment] 2020-03-05 08:25
@mhutchie I think you didn't understand me.
> Commit Detail View shows all of the changes that were merged from one branch into another

But In my case **there were no changes in develop compared to the master branch**. Again, I merged **`master` into `develop`**. `master` -> `develop`. Please, read carefully _master into develop_. **Develop branch already had everything that was in master** before the merge except for 1 file diff.

**Comment by alexeychikk** [comment] 2020-03-05 08:28
@mhutchie Your diff would be correct if I merged `develop` into `master` but that is not the case. I merged `master` into `develop`.

**Comment by alexeychikk** [comment] 2020-03-05 08:36
@mhutchie I think there is a bug in the way you select "the first parent", maybe you select it from the wrong branch, I don't know. Again, I merged branch that adds no changes to the `develop` branch whatsoever. Why would I see any diff?

**Comment by alexeychikk** [comment] 2020-03-05 08:41
@mhutchie Just look at the screenshot, your diff shows, that I modified and even added files to the `develop` branch with this merge commit. **But that is not true.** All of those files were already in `develop`.

**Comment by alexeychikk** [comment] 2020-03-05 08:42
@mhutchie I don't need the option to see resolved conflicts. I need to see the correct diff.

**Comment by alexeychikk** [comment] 2020-03-05 08:55
@mhutchie Please click on the merge commit on the `develop` branch in this repo in your extension
https://github.com/alexeychikk/git-graph-diff-bug
And try to explain to me, why merge commit shows that `b.js` was added with the merge when it actually was already created in the `develop` branch.

**Comment by alexeychikk** [comment] 2020-03-05 09:01
@mhutchie And then open the diff for this merge commit in `Sublime Merge` or even in the github itself https://github.com/alexeychikk/git-graph-diff-bug/commit/f2ffa2124b3acf7918d17db1efdbd9e84cc17c48
You can clearly see that nothing was added. And that's a correct behavior.

**Comment by mhutchie** [comment] 2020-03-05 09:27
Thanks for the repository containing an example of the incorrect behaviour you found. I can now see the issue you're describing, and am working on a fix for it. It will be available in a beta release for you to use soon.

**Comment by alexeychikk** [comment] 2020-03-05 10:04
@mhutchie Besides that your extension is really awesome and I greatly appreciate your work. Thanks.

**Comment by mhutchie** [comment] 2020-03-05 11:06
I've corrected the logic so that the Commit Details View now returns the files with differences between the commit and it's first parent. In my first response I forgot that the "first parent" logic was for when the Visual Studio Code Diff View is opened, *not* the Commit Details View. From what I can see, the example repository you provided now performs identically to GitHub.

Please follow the instructions below to install the beta release, and confirm that this "first parent" logic now meets your expectations. If not, please provide another example repository to illustrate the scenario

This will be available in v1.22.0.

You can download [v1.22.0-beta.5](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.22.0-beta.5), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).

**Closed by mhutchie** 2020-03-05 11:06 UTC
Labels: bug

**Comment by alexeychikk** [comment] 2020-03-05 11:39
@mhutchie `.vsix` file is missing in the release's assets.

**Comment by mhutchie** [comment] 2020-03-05 11:52
@alexeychikk The upload failed, I've reattached the `.vsix` file.
