### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rbadapanda** [mhutchie/vscode-git-graph#112] opened 2019-06-22 03:57 UTC
[mhutchie.git-graph-unresponsive.cpuprofile.txt](https://github.com/mhutchie/vscode-git-graph/files/3316498/mhutchie.git-graph-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `git-graph`
- Extension Version: `1.8.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.36.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mhutchie** [comment] 2019-06-22 05:46
I've had a look at the CPU profile, and there doesn't appear to be anything in it that indicates an issue caused by the extension itself.

When do you get this unresponsive behaviour, and does this occur consistently or is it a one-off?

If it is repeatable, does this occur in VSCode 1.36.0 (the non insider version)?

**Comment by mhutchie** [comment] 2019-06-26 00:56
I'm closing this issue for now as:
* You have not provided the necessary information I requested (so I can't investigate what may have caused this for you).
* There is nothing in the CPU profile you provided that indicates an issue caused by the extension itself (from what I can see).
* This seems like a one-off occurrence, as the 53,000+ other users haven't reported similar behaviour at any time since this extension was first published.

**Closed by mhutchie** 2019-06-26 00:56 UTC
Labels: needs more info
