### ISSUE TITLE
branch switching not working or very delayed

### ISSUE THREAD

**Issue by HitLuca** [mhutchie/vscode-git-graph#275] opened 2020-03-06 08:49 UTC
**Describe the Bug**
When double clicking on a branch on git graph, vscode doesn't always switch to it, and when it happens usually is after a long delay

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Open git graph, have one branch checked out and another one for testing
2. Double click on a branch
3. The branch now is bold, but vscode hasn't actually changed branch
4. In some cases, after waiting some tens of seconds, the branch is successfully changed

**Expected Behaviour**
Double clicking on a branch should switch to it immediately

**Environment**
 - Git Graph Extension Version: 1.21.0
 - Visual Studio Code Version: 1.42.1
 - Operating System: MacOS 10.14.5

This bug isn't very easy to reproduce, as subsequent tests obtain different results
- branch switched immediately
- branch switched after a couple of seconds
- branch not switched
-branch switched after tens of seconds

**Comment by mhutchie** [comment] 2020-03-06 09:15
Hi @HitLuca,

From what you've said, when you double click on a branch (that isn't currently checked out) in the Git Graph View, the branch is bolded. Because it is bolded, that indicates that the branch *was* checked out by Git, and when the Git Graph View automatically refreshed, Git confirmed the branch was successfully checked out. This indicates that Git Graph is functioning completely as expected, the branch was been checked out in the repository immediately when you double clicked.

The delay in the branch indicated by Visual Studio Code as checked out (I assume you mean Visual Studio Code's Status Bar item), is due to how Visual Studio Code is monitoring the File System for events within the repository. Visual Studio Code uses these events to do a background refresh, and update the branch it indicates as currently checked out. File System events in Visual Studio Code are notoriously unpredictable, which explains why your test results varied widely.

Visual Studio Code's monitoring of the repository (and consequent updates to their Status Bar Item) is completely unrelated to Git Graph. There also isn't anything I can do in Git Graph to make Visual Studio Code refresh more consistently / faster.

FYI: You should be able to observe the same delayed behaviour in Visual Studio Code's Status Bar item if you run the Git command `git checkout <other-branch>` numerous times. (this is all that Git Graph is doing when you double click on a branch)

I'll close this issue as from what you've described it is unrelated to Git Graph, and I'm unable to make any changes that would make Visual Studio Code update any faster.

**Closed by mhutchie** 2020-03-06 09:15 UTC
Labels: bug

**Comment by HitLuca** [comment] 2020-03-06 09:20
Thank you for the quick answer, if nothing can be done then I will just switch branch using the vscode button. For some reason a bunch of months ago it was instantaneous, could it be that it got slower due to a bigger project or multiple projects open?

**Comment by HitLuca** [comment] 2020-03-06 09:24
Also, if the behavior is what you described, vscode doesn't actually run proper git commands when triggering them from the command palette: this is because if I switch branch (and the switch is not recognized by vscode) and quickly call the `Git: Pull` command, I will get an error that doesn't happen when the branch is successfully recognized. This makes me think that a `Git: Pull` doesn't simply run a `git pull` but instead tries to pull the current checked out branch by name

**Comment by mhutchie** [comment] 2020-03-06 09:28
Definitely, both of those factors could increase the delay between when the new branch is checked out and when it is reflected in the Visual Studio Code Git Extension!

Unless you use the Visual Studio Code Git Extension itself to checkout branches (and not anything external - e.g. the `git` command line or Git Graph), there will inevitably be a delay to due to Visual Studio Code's File System Watcher. Generally speaking it should be almost instantaneous, however numerous factors like the ones you mentioned that may delay it.
