### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 0aqz0** [mhutchie/vscode-git-graph#444] opened 2020-12-24 12:44 UTC
- Issue Type: `Performance`
- Extension Name: `git-graph`
- Extension Version: `1.28.0`
- OS Version: `Linux x64 5.4.0-58-generic`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
[mhutchie.git-graph-unresponsive.cpuprofile.txt](https://github.com/mhutchie/vscode-git-graph/files/5739568/mhutchie.git-graph-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mhutchie** [comment] 2020-12-24 19:26
After reviewing the cpu profile, I can see that the function that occupied the majority of the profile period was an event handler that receives events when files are created on the file system. It's used to detect when new Git repositories are created in the Visual Studio Code workspace, so they can be automatically included in Git Graph. The event handler is extremely simple ([see it here](https://github.com/mhutchie/vscode-git-graph/blob/5003103f6b967235ce2dbc584c4f8f8aad2ba085/src/repoManager.ts#L532-L537)), yet in the profile your computer seems to be spending quite a long time on it (not on methods called from it, the time is spent on this method itself). There isn't an explanation for this within the extension's code, so I'm inclined to believe that either: your computer was busy doing other tasks at the time (so everything on your computer was running slower than usual), or an enormous volume of file system creation events were generated (and the extension had to spend the time processing them all).

I've only had one other report (in almost two years & 889,000 users) of degraded performance caused by these event handlers, so I'm inclined to believe this was a one-time occurrence, and not a recurring issue with Git Graph that I need to resolve. I'll close this issue for this reason.

However, if you continue to receive this multiple times, please provide additional cpu profiles so I can look into this further.

**Closed by mhutchie** 2020-12-24 19:26 UTC
