### ISSUE TITLE
Unable to open terminal by hotkey

### ISSUE THREAD

**Issue by GOST-UA** [mhutchie/vscode-git-graph#120] opened 2019-07-04 11:00 UTC
**Describe the bug**
When I'm trying to open Integrated Terminal using the hotkey (ctrl+`) while git-graph window is active, vscode just flickers for a moment and nothing else happens.

**What does the bug relate to**
List the area(s) this issue relates to, for example:
- Graph Rendering
- Degrade of vscode functions

**To reproduce**
1. Open git-graph window
2. Press "Toggle Integrated Terminal" hotkey
3. See error

**Expected behavior**
Integrated Terminal shows as it should.

**Environment**
 - OS: Ubuntu 16.04 Linux x64 4.15.0-54-generic on Virtual Box (Host OS Windows 10)
 - Visual Studio Code Version: 1.36.0

**Additional context (optional)**
It's really strange because in vscode on Windows all work fine.

P.S. There is a typo in the word 'behavior' in the issue Bug report template :smile:

**Comment by GOST-UA** [comment] 2019-07-04 11:03
Also, if Terminal already opened then I can switch focus to it, close it and after that described behavior occurs.

**Comment by mhutchie** [comment] 2019-07-04 12:00
I've followed the steps you've provided to reproduce this issue, and haven't been able to observe the behaviour you've described in VSCode Windows & Mac, or VSCode Insiders Windows, Mac & WSL. It seems to be isolated to the specific platform you're using. No one else using this extension has reported any issues like this.

From what you have described, the keyboard shortcut is recieved by VSCode, and VSCode then attempts to execute the command which fails (and VSCode flickers). This indicates that Git Graph is not blocking / affecting the keyboard shortcut itself, as VSCode does start executing the "Toggle Integrated Terminal" command. At the time the command fails, VSCode is running the code of the command (Git Graph has nothing to do with this).

I expect that this behaviour would also occur with any extension contributing a [Webview](https://code.visualstudio.com/api/extension-guides/webview), when the Webview is open (the main Git Graph view is a Webview). Numerous platform specific issues (like this one) affecting all extensions using Webview's have happened before, i.e. it's not uncommon. I'd suggest installing another extension that uses a Webview, such as [Edit csv](https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv), to see if you can observe the same behaviour with it.

I'm closing this issue for now as there is no way I could fix this behaviour from within the Git Graph codebase, and it would have to be fixed in Visual Studio Code itself.  Please raise it as a bug in the https://github.com/Microsoft/vscode repository, so they can be made aware of it & fix it.

Please let me know what you find out, I'd be curious to know what caused this issue.

**Closed by mhutchie** 2019-07-04 12:00 UTC
Labels: bug

**Comment by GOST-UA** [comment] 2019-07-04 12:27
Thanks for a quick response!
I just had tested this behavior with another extension that uses Webview (_Edit csv_ as you suggest) and yes, I observed the identical issue. 
Also, I found a [ticket](https://github.com/microsoft/vscode/issues/75421) in the https://github.com/Microsoft/vscode repo that describes a similar issue.
