### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by scott-knight** [mhutchie/vscode-git-graph#252] opened 2020-01-21 23:38 UTC
- Issue Type: `Performance`
- Extension Name: `git-graph`
- Extension Version: `1.21.0`
- OS Version: `Darwin x64 19.2.0`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/sknight-blc/mhutchie.git-graph-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

[mhutchie.git-graph-unresponsive.cpuprofile.txt](https://github.com/mhutchie/vscode-git-graph/files/4094449/mhutchie.git-graph-unresponsive.cpuprofile.txt)

My apologies for not providing what you needed the first time. This may be a one-off. I had VSCode open in the background, locked my computer, and walked away for a meeting. After an hour or so, I came back, unlocked my Mac and the prompt for the error was in VSCode. I simply clicked the report button. I have uploaded the details as requested.

**Comment by mhutchie** [comment] 2020-01-21 23:46
Please provide the CPU Profile as required in the template you have used, so I can attempt to replicate the behaviour you have observed.

Also, please provide the following information to help me attempt to replicate & identify the cause of this:
* When did you get this? (e.g on VSCode startup, performing a specific task with Git Graph)
* Are you consistently getting this behaviour, or is it a one-off?

No one else has reported that the extension causes high CPU load for Git Graph, so I'm inclined to believe this is an isolated event unless you can provide information to the contrary.

**Comment by mhutchie** [comment] 2020-01-22 00:32
Thanks for providing the extra information.

After looking at the CPU Profile, the reason Visual Studio Code reported High CPU usage was:
* Git Graph monitors file system events in the open workspace folders so that it can detect if repositories are added or deleted on the file system. This is done through a method provided by the Visual Studio Code API for extensions.
* The provided CPU profile indicates that Visual Studio Code sent a large number of file creation events to the extension, which the extension processed appropriately.
* It appears that due to the large number of file creation events which the extension had to process, it exceeded the "High CPU Usage" threshold set by Visual Studio Code. This is inevitable and unavoidable as the extension has to process each event (it can't help if there are heaps of events though for it to process).
    * A possibility I think may have occurred is that the volume of file creation events were from the OS or Visual Studio Code queuing them until you unlocked your Mac, and then they were all sent to the extension at once.
* There is absolutely no indication that the extension was behaving incorrectly in any way.

For these reasons, I believe this to be a one-off event and will close this issue.

FYI: As there are over 250,000 users of Git Graph, this would have definitely come up many times before over the last year if there was an underlying issue that needed to be addressed.

**Closed by mhutchie** 2020-01-22 00:32 UTC
Labels: needs more info
