### ISSUE TITLE
Panels menu overlaps main window menu

### ISSUE THREAD

**Issue by albertosantini** [mhutchie/vscode-git-graph#247] opened 2020-01-15 13:28 UTC
**Describe the Bug**
Menu is overlapped by terminal header (see screenshot) when maximized and only when Git Graph is opened.

**Steps to Reproduce**

- Open Git Graph
- Open a terminal (for instance, or Problems, Output panels)
- Maximize panel size of the terminal

**Expected Behaviour**

No overlapping.

![image](https://user-images.githubusercontent.com/328179/72437449-06b5dc00-37a3-11ea-96d7-22d6db1cfb07.png)

**Environment**
 - Git Graph Extension Version: 1.21.0
 - Visual Studio Code Version: 1.41.1
 - Operating System: Windows 10

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/328179/72437089-47f9bc00-37a2-11ea-8b8a-f2eb8ed4d1f2.png)

**Additional Context (optional)**
No additional context.

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment] 2020-01-15 13:43
Duplicate of #234.

The extension uses a [Webview](https://code.visualstudio.com/api/extension-guides/webview) in Visual Studio Code for the main Git Graph View. The behaviour you're observing is to do with the incorrect positioning of the Webview over the Visual Studio Code Header, and this would occur for any Webview from any extension. Visual Studio Code manages the positioning and lifecycle of Webviews, while extensions only contribute the content within it.

As this is a Visual Studio Code bug, **please raise it as a bug in the [vscode](https://github.com/Microsoft/vscode) repo**, so Microsoft can fix it. Since they upgraded to Electron 6.x in VSCode 1.40.0, there have been numerous frustrating bugs to do with their handling of Webviews, affecting all extensions that use Webviews.

I'm closing this bug as it is caused by, and needs to be fixed in Visual Studio Code, and there is nothing I can do within the extension to fix it in the interim.

**Closed by mhutchie** 2020-01-15 13:43 UTC
Labels: bug

**Comment by albertosantini** [comment] 2020-01-16 08:14
Thanks for the details. Sorry for the noise. I didn't find it.
