### ISSUE TITLE
"Failed to register a ServiceWorker" on VSCode 1.61.0

### ISSUE THREAD

**Issue by johan13** [mhutchie/vscode-git-graph#577] opened 2021-10-08 14:05 UTC
**Describe the Bug**
After upgrading to VSCode 1.61.0, git-graph no longer works. I get a blank tab and a error pop-up in the lower right corner saying:
```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

**Steps to Reproduce**
Open any project with a git repo and click "Git Graph" in the status bar or the "View Git Graph" button in the Source Control sidebar.

**Expected Behaviour**
The git-graph UI should appear.

**Environment**
 - Git Graph Extension Version: 1.30.0
 - Visual Studio Code Version: 1.61.0
 - Operating System: Ubuntu 20.04

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/643284/136570503-a0a662f3-b4e6-4476-b6ef-d5faccc9d75a.png)

**Additional Context (optional)**

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment] 2021-10-08 14:09
Duplicate of #524 - this is an ongoing Visual Studio Code bug that Microsoft haven’t been able to resolve.

**Closed as completed by mhutchie** 2021-10-08 14:09 UTC
Labels: vscode-bug, duplicate
