### ISSUE TITLE
Header of GitGraph overlaps Visual Studio Code header

### ISSUE THREAD

**Issue by YauhenPylAurea** [mhutchie/vscode-git-graph#234] opened 2019-12-18 17:30 UTC
**Describe the Bug**
a header of the extension overlaps VSC header.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Initial state
![image](https://user-images.githubusercontent.com/42114592/71108790-1b16b100-21c4-11ea-8030-b7e19f6efcfa.png)
2. Click on Maximize Panel Size 
![image](https://user-images.githubusercontent.com/42114592/71108835-308bdb00-21c4-11ea-849f-e2d5f551dd4c.png)
3. See error
![image](https://user-images.githubusercontent.com/42114592/71108873-4ac5b900-21c4-11ea-989b-10c3051e1f24.png)

**Expected Behaviour**
The header of the extension should not be visible

**Environment**
 - Git Graph Extension Version: 1.19.1
 - Visual Studio Code Version: 1.41.0
 - Operating System: Win10

**Screenshots (optional)**
Below

**Additional Context (optional)**
-

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment] 2019-12-18 20:51
Another user previous reported this problem on a Mac OS.

The extension uses a [Webview](https://code.visualstudio.com/api/extension-guides/webview) in Visual Studio Code. The behaviour you're observing is to do with the incorrect positioning of the Webview over the Visual Studio Code Header, and this will occur for any Webview from any extension. Visual Studio Code manages the positioning and lifecycle of Webviews, while extensions only contribute the content within it.

As this is a Visual Studio Code bug, **please raise it as a bug in the [vscode](https://github.com/Microsoft/vscode) repo**, so Microsoft can fix it. Since they upgraded to Electron 6.x in VSCode 1.40.0, there have been numerous frustrating bugs to do with their handling of Webviews, affecting all extensions that use Webviews.

I'm closing this bug as it is caused by, and needs to be fixed in Visual Studio Code, and there is nothing I can do within the extension to fix it in the interim.

**Closed by mhutchie** 2019-12-18 20:51 UTC
Labels: bug

**Comment by YauhenPylAurea** [comment] 2019-12-18 21:01
Thank you very much for your explanation.
