### ISSUE TITLE
Compare to "local" or "workspace"  rather then just two commits.

### ISSUE THREAD

**Issue by danocharron** [mhutchie/vscode-git-graph#474] opened 2021-03-09 15:06 UTC
First I love you extension.
The power of comparing commits is what I like.

It would be nice to click on an older commit and compare to the local or working files such that the folder is pointing to the actual files not a copy.

This way you can make changes to the local / working files.

**Comment by mhutchie** [comment] 2021-03-09 20:30
Hi @danocharron,

This is a duplicate of #457, so I’ll close this one.

#457 is currently almost completed, so it will be available in a beta release within the next day.

**Closed by mhutchie** 2021-03-09 20:30 UTC
Labels: improvement

**Comment by mhutchie** [comment] 2021-03-10 09:43
This will be available in v1.30.0.

If you'd like to use it before the next release, you can download [v1.30.0-beta.1](https://github.com/mhutchie/vscode-git-graph/releases/tag/v1.30.0-beta.1), and install it following the instructions provided [here](https://github.com/mhutchie/vscode-git-graph/wiki/Downloading-&-Installing-Releases#manual-installation).
