### ISSUE TITLE
Paste not working

### ISSUE THREAD

**Issue by owzim** [mhutchie/vscode-git-graph#296] opened 2020-04-21 10:18 UTC
Paste is not working on the following modals (more not tested):

## Create branch

![image](https://user-images.githubusercontent.com/1720088/79854065-2c1d3c00-83c9-11ea-9d9c-dc3691fb2e2d.png)

**Steps to Reproduce**

1. right click on any commit > create branch
2. try to paste from the clipboard, nothing happens

## Add remote

![image](https://user-images.githubusercontent.com/1720088/79854082-33dce080-83c9-11ea-88a4-e738b0d9f8f5.png)

**Steps to Reproduce**

1. click on 'repository settings' cog in the upper right corner of the graph overview
2. click on '+ add remote'
3. try to paste into any of the input fields from the clipboard, nothing happens

**Expected Behaviour**

Text from the clipboard is pasted into the focused input field

**Environment**
 - Git Graph Extension Version: `1.22.0`
 - Visual Studio Code Version: `1.43.1`
 - Operating System: macOS `10.14.6`

**Comment by mhutchie** [comment] 2020-04-21 12:39
Hi @owzim,

Being able to paste text into any field is quite a basic core operation that is used by the vast majority of users. It is also implemented by the Electron instance running Visual Studio Code, and I can’t think of any way that the extension could possibly prevent this built in behaviour from operating.

I’ve tested pasting into text fields on Windows, Mac, and Linux platforms and never observed any issues with it not working. I also couldn’t replicate the behaviour you’re observing on my Mac computer by following your detailed reproduction steps. I also tried pasting into many other text fields on dialogs and it worked first time, every time.

If this were a bug, I would have expected that many other of the extensions 380,000 users to have reported it in the time since the extension was first published over the year ago. There haven’t been any changes to how the text fields operate since day one of the extension that could feasibly introduce the behaviour your observing. Not a single person has ever reported any issues with pasting. The closest example I’ve heard was one user who had remapped there Mac command keys (and they just weren’t using the correct remapped shortcut they had defined).

I’ll close this issue for now, as based on all the information I have it seems to be an isolated issue affecting only yourself (and is more than likely something to do with your specific environment setup and configuration). Of course if I do find out any information to the contrary, or another user reports the same behaviour, I would immediately reopen, fix, and release this issue ASAP as it is such a fundamental operation that should always work.

**Closed by mhutchie** 2020-04-21 12:39 UTC
Labels: bug

**Comment by owzim** [comment] 2020-04-23 12:41
@mhutchie thanks for the extensive response. I'll have a look and try to isolate the issue.

**Comment by AMartsinkevich** [comment] 2022-05-04 15:36
Still not working -)
Latest versions, Winx64

F1: Git Graph: View Git Graph (git log)
Right Click -> Copy
Try to Paste somewhere -> Old clipboard pasted

![image](https://user-images.githubusercontent.com/48548717/166717026-3246d8e8-f8ef-497a-858b-6bc08b9b29ee.png)
