### ISSUE TITLE
Filter/highlight commits for a specific directory

### ISSUE THREAD

**Issue by Janneman96** [mhutchie/vscode-git-graph#411] opened 2020-11-11 15:52 UTC
**Describe the feature that you'd like**
I'd like to be able to highlight the commits that did something to a specific (sub)directory. It could be a searchbar, then the commits that don't have any changes to that directory would be greyed out like the merge commits are now.

**Additional context (optional)**
I'm working for a big company, we've got releases every couple of months. The releases tend to get pretty big. We've ran into an issue and we want to compare the changes from the last release to the current release for a specific folder.

**Comment by mhutchie** [comment] 2020-11-12 07:36
Hi @Janneman96,

I think this feature request is for the same core functionality as the existing feature request #70 (bullet point 2), although your suggestion is definitely an alternative way to implement it.

If so, please let me know as I'd prefer just to keep the existing feature request open and close this one (so there aren't two that are tracking the delivery of the same functionality). If not, would you please provide some more detail to clarify how the underlying functionality you're requesting differs from the existing feature request.

**Comment by mhutchie** [comment] 2020-11-14 07:54
I’m closing this feature request as I believe it is a duplicate of an existing feature request, and you haven’t responded with information to the contrary.

If you don’t think this is a duplicate, please reply with the information I previously requested, and I’d happily reopen this feature request.

**Closed by mhutchie** 2020-11-14 07:54 UTC
Labels: feature request
