### ISSUE TITLE
The Git Graph tab closes when VS Code is restarted

### ISSUE THREAD

**Issue by FabienSailliet** [mhutchie/vscode-git-graph#458] opened 2021-02-05 21:46 UTC
**Describe the Bug**
When closing and reopening Visual Studio Code, if the Git Graph tab was opened, it is not restored.

**Steps to Reproduce**
1. Open the Git Graph tab by clicking `Git Graph` in the status bar
2. Close Visual Studio Code
3. Start Visual Studio Code
4. There is no opened Git Graph tab

**Expected Behaviour**
The editor should start on the Git Graph tab, or at least the Git Graph tab should be there.

**Environment**
 - Git Graph Extension Version:1.28.0
 - Visual Studio Code Version: 1.53.0
 - Operating System: Kubuntu 20.04

**Comment by mhutchie** [comment] 2021-02-05 22:09
This is a duplicate of #403.

Please see [my comment](https://github.com/mhutchie/vscode-git-graph/issues/403#issuecomment-715309655) for an explanation of why Git Graph currently doesn't support this.

**Closed by mhutchie** 2021-02-05 22:09 UTC
