### ISSUE TITLE
Opening problem

### ISSUE THREAD

**Issue by jboucly** [mhutchie/vscode-git-graph#306] opened 2020-05-20 07:40 UTC
**Describe the Bug**

When I open git graph it doesn't open. It displays 3 lines but not the general app ...
This happens regularly, the only way I have found to fix this problem is to close and reopen it at least 3 to 4 times so that it displays properly.

**Steps to Reproduce**
1. Click on _Git Graph_ button bottom VsCode or Click on _Git Graph_ button in the git tab.
2. See the result : 
<img width="271" alt="Git_Graph_—_ngzorro-8" src="https://user-images.githubusercontent.com/33218155/82418669-90d9be00-9a7d-11ea-8683-32c6513db2cc.png">

**Expected Behaviour**

![demo_gif__1208×682_](https://user-images.githubusercontent.com/33218155/82418799-bb2b7b80-9a7d-11ea-8537-df96e549961e.png)

**Environment**
 - Git Graph Extension Version: 1.22.0
 - Visual Studio Code Version:  1.45.1
 - Operating System: Mac OS Catalina Version 10.15.2

**Comment by mhutchie** [comment] 2020-05-20 09:29
Thanks for reporting that you’re experiencing this issue!

Unfortunately this is being caused by a Visual Studio Code Webview bug that was introduced in a recent release of Visual Studio Code. This is already in the process of being fixed by Microsoft, and I’m hoping it will be available soon.

I’m closing this issue as there is nothing I can do within Git Graph to resolve this bug, as it is caused, and being resolved in Visual Studio Code itself.

**Closed by mhutchie** 2020-05-20 09:29 UTC

**Comment by jboucly** [comment] 2020-05-20 09:32
Okey Thanks !

**Comment by joshuatrevissmith** [comment] 2020-06-07 19:23
For what it's worth, this issue was resolved for me when I upgraded VS Code Insiders from an unknown version to 1.46.0-insider from 2020-06-05.
