### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Taccosting** [mhutchie/vscode-git-graph#533] opened 2021-06-24 15:26 UTC
- Issue Type: `Performance`
- Extension Name: `git-graph`
- Extension Version: `1.30.0`
- OS Version: `Windows_NT x64 6.1.7601`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ADMINI~1\AppData\Local\Temp\mhutchie.git-graph-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by mhutchie** [comment] 2021-06-24 22:58
Hi @Taccosting,

You haven't provided the CPU profile highlighted by the yellow exclamation emoji's in the template you used - this makes it impossible for me to investigate this further. All I know from the information you've provided is that the extension was slow to start once, for one user, and have no context to know what could have possibly caused it.

I've only had occasional reports of Git Graph causing high cpu load (this is the second this year), so I'm inclined to believe this was a one-time module loading anomaly (likely hardware induced), and not a recurring issue with Git Graph that I need to resolve. I'll close this issue for this reason.

However, if you've received this multiple times, please provide additional cpu profiles so I can attempt to investigate the root cause further.

**Closed as completed by mhutchie** 2021-06-24 22:58 UTC
