### ISSUE TITLE
Add icon to Activiy Bar

### ISSUE THREAD

**Issue by kanlukasz** [mhutchie/vscode-git-graph#118] opened 2019-07-03 19:42 UTC
**Desc:**
I think it would be useful if you could add `Git Graph` icon to `Activity Bar`
What do you think about it?

**Example:**
![obraz](https://user-images.githubusercontent.com/30685349/60620357-486ccf80-9ddb-11e9-91c9-586540180c37.png)

**Comment by mhutchie** [comment] 2019-07-03 23:04
Closing as a duplicate of #75, which was closed because:

> After looking into this and doing some tests, it appears that in order to add a button/icon to the Activity Bar, the extension must contribute a view container with at least one view to the VS Code Sidebar, as described [here](https://code.visualstudio.com/api/references/contribution-points#contributes.viewsContainers). The Activity Bar buttons/icons cannot be used to trigger an arbitary extension command (like [StatusBarItem](https://code.visualstudio.com/api/references/vscode-api#StatusBarItem)'s can). 
> 
> Creating a Side Bar view is not something I intend to do with this extension in the near future, as I haven't found any functionality that can't be incorporated best, intuitively & visually in the [Webview](https://code.visualstudio.com/api/references/vscode-api#Webview) (not a sidebar view) that Git Graph uses.
> 
> I'll keep an eye out for if the VS Code API allows this in the future, in which case I can add it then, or if new Git Graph functionality is requested that would be best suited to a new Side Bar view.

**Closed by mhutchie** 2019-07-03 23:04 UTC
Labels: feature request
