### ISSUE TITLE
Statusline is not updated when checking out a branch from gitgraph window

### ISSUE THREAD

**Issue by McPan** [mhutchie/vscode-git-graph#472] opened 2021-03-04 16:11 UTC
[Statusline is not updated when checking out a branch from gitgraph window. Not sure if it's a gitgraph or maybe a VS-Code bug. Using current VS-Code version 1.53.2

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Create a new git repository
2. Commit some files to current branch 'master'
3. Create and checkout a second branch, i.e. 'develop'
4. Commit some files to current branch 'develop'
5. Checkout branch 'master' from gitgraph window

Gitgraph window indicates 'master' as current branch, VS-Code file explorer shows only initially committed files, it's really branch 'master'. VS-Code's statusline at the bottom is still indicating branch 'develop' until restart of VS-Code.

**Expected Behaviour**
VS-Code statusline should indicate current branch.

**Environment**
 - Git Graph Extension Version: v1.29.0
 - Visual Studio Code Version: 1.53.2
 - Operating System: Win10 x64 20H2

**Screenshots**
![grafik](https://user-images.githubusercontent.com/60808286/109993351-7c189f00-7d0c-11eb-9654-19c61258f909.png)
![grafik](https://user-images.githubusercontent.com/60808286/109993380-85a20700-7d0c-11eb-96c0-155bf6e3a7e3.png)

**Comment by McPan** [comment] 2021-03-04 18:44
Just installed new VS-Code release 1.54, same behavior.

**Comment by mhutchie** [comment] 2021-03-04 20:15
This is a duplicate of #275, #280 & #282.

Please see [this previous comment of mine](https://github.com/mhutchie/vscode-git-graph/issues/282#issuecomment-602097824), which explains the cause of the behaviour you're observing (a Visual Studio Code Bug).

**Closed by mhutchie** 2021-03-04 20:15 UTC
Labels: vscode-bug

**Comment by McPan** [comment] 2021-03-05 16:20
Aw, my fault. Didn't check the closed issues before.
