### ISSUE TITLE
GHit Graph stopped working after code upgrade

### ISSUE THREAD

**Issue by steho** [mhutchie/vscode-git-graph#514] opened 2021-05-17 16:14 UTC
Hello all,
I am using Git Graph on my Linux box (Debian 9, code 1.56.0-1620166262) and am very happy about this gorgeous  tool.
Today I upgraded code to 1.56.2-1620838498 as offered by apt and Git Graph stopped working with the message:
```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.
```
Downgrading to the previous version fixed the problem, but that can only be a temporary solution.

**Comment by mhutchie** [comment] 2021-05-17 21:00
This is a duplicate of #508 & #511 - This is a Visual Studio Code Bug that has been raised with Microsoft.

**Closed as completed by mhutchie** 2021-05-17 21:00 UTC
Labels: vscode-bug, duplicate
