### ISSUE TITLE
Changes of selected commits

### ISSUE THREAD

**Issue by freddi301** [mhutchie/vscode-git-graph#446] opened 2020-12-29 12:43 UTC
**Describe the feature that you'd like**
Selecting (click then shit+click) two commits (on the same chain) i would like to see the changes made only in those commits

**Additional context (optional)**
I use this feature a lot with gitkraken

**Comment by mhutchie** [comment] 2020-12-29 20:59
Hi @freddi301,

Thanks for raising this feature request!

This is a duplicate of #169, which was closed and moved to the backlog due to:
* A lack of interest from the user community (only two people indicated they wanted this functionality in an 11 month period).
* The complexity involved to implement it (described in the second half of [this comment](https://github.com/mhutchie/vscode-git-graph/issues/169#issuecomment-526131930)).

I'll close this request as it's a duplicate, however it's good to know another user is wanting this functionality.

Note to users reading this in the future: If you'd like this functionality, please reply to this thread to express your interest. I'd happily re-open and add this feature if there was any indication it would be used by a decent number of users.

**Closed by mhutchie** 2020-12-29 20:59 UTC
Labels: backlog, feature request
