### ISSUE TITLE
Diff failing for some oddly named file

### ISSUE THREAD

**Issue by marcellourbani** [mhutchie/vscode-git-graph#192] opened 2019-10-07 23:15 UTC
Diff view fails to open for some file with # characters in them.

**Steps to Reproduce**
Clone [this repository](https://github.com/marcellourbani/btidummy)
1. Open it in vscode
2. Click on git graph
3. Open the last commit
4. Click on the only committed file

**Expected Behaviour**
A diff will open, but I get an error instead

**Environment**
 - Git Graph Extension Version: 1.16.0
 - Visual Studio Code Version: 1.38.1
 - Operating System: Arch linux

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/2453277/66355784-73c60400-e960-11e9-906f-74af38cb6f59.png)

**Additional Context (optional)**
These names are extremely unlikely in regular scenarios but are the norm with SAP ABAP when using namespaces
I think it's a bug in vscode API, but will follow  up with a pull request with a workaround

**Comment by mhutchie** [comment] 2019-10-08 00:00
Thanks for raising this issue and raising a PR for it, it's much appreciated!

I found that `vscode.Uri.parse` will interpret `#`'s in the filenames and put them (and everything after it) into the URI's fragment field. Instead, `vscode.Uri.file` should be used as it will not interpret `#` or `?` in filenames (see the Visuals Studio Code [API documentation](https://github.com/microsoft/vscode/blob/f52667b2493a71919b5765037d0eb05dfcf1400a/src/vs/vscode.d.ts#L1249-L1271)). I simply misused `vscode.Uri.parse` when I should have used `vscode.Uri.file`. (It's definitely not a bug in the VSCode API)

Please see my comment on your PR for more details.

This fix will be release in 1.17.0 (which will be released in the next few hours).

**Closed by mhutchie** 2019-10-08 00:00 UTC
Labels: bug
