### ISSUE TITLE
Display: Blue screen error

### ISSUE THREAD

**Issue by RRoundTable** [mhutchie/vscode-git-graph#433] opened 2020-12-14 04:48 UTC
**Describe the Bug**

When I click git graph icon, I faced blue screen.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Click on git graph

**Expected Behaviour**

**Environment**
 - Git Graph Extension Version: [e.g. 1.13.0]
 - Visual Studio Code Version: [e.g. 1.37.1]
 - Operating System: [e.g. Mac]

**Screenshots (optional)**
Add any screenshots showing the bug.
![image](https://user-images.githubusercontent.com/27891090/102041492-f3781a00-3e12-11eb-933c-3c05ba08c83c.png)

**Additional Context (optional)**

⚠ Please make sure you complete all of the required sections of this template. Without this required information, it will be harder to replicate this bug, and cause additional delays in resolving it.

**Comment by mhutchie** [comment] 2020-12-14 05:07
Hi @RRoundTable,

What versions of Git Graph & Visual Studio Code are you using?

Does this occur every time you open Git Graph, or was this a one-time occurrence?

If it occurs all the time: Git Graph uses a Visual Studio Code [Webview](https://code.visualstudio.com/api/extension-guides/webview) to render its content (standard HTML + CSS + JS). Would you try installing another extension that uses a Webview to see if the same behaviour occurs in it? ("Edit csv" is one that's easy to use, just install the extension and try opening a CSV file with the "Edit csv")

There's nothing in Git Graph that would cause this to occur, and I haven't had any reports of anything similar since the extension was first created. This seems to suggest it's something specific to your device. If you could please provide the above information, hopefully we can work out what's going on.

**Comment by mhutchie** [comment] 2020-12-14 11:14
After inspecting some of the coloured artefacts in the screenshot you provided, I've spotted many features that make it impossible for this to be caused by CSS styles. Therefore, I'm even more confident it's not style related, and most like caused by your hardware / configuration. As none of the other Git Graph users have ever reported this, I'm inclined to believe this is an extremely isolated occurrence.

As you haven't provided the additional information I requested, and there's no indication that this is an issue with Git Graph, I'll close this issue. If you can provide the requested information, I'd be happy to try to help diagnose the root cause of the problem.

**Closed by mhutchie** 2020-12-14 11:14 UTC
Labels: needs more info

**Comment by RRoundTable** [comment] 2020-12-14 14:22
> Does this occur every time you open Git Graph, or was this a one-time occurrence?

> I've spotted many features that make it impossible for this to be caused by CSS styles. 

Thanks to reply. It occured every time I opened git graph. But, now I can't reproduce this error.
I assume this is because I remove unnecessary features(branchs) in local.

Thanks to your help!

**Comment by mhutchie** [comment] 2020-12-21 01:01
Other Visual Studio Code users are reporting similar distortions with very similar blue artefacts in this Visual Studio Code issue https://github.com/microsoft/vscode/issues/69665#issuecomment-740928211. In the screenshot in the linked comment, the artefacts are shown over other parts of the Visual Studio Code interface, ruling out that this has anything to do with Git Graph. Reading some of the other comments in the linked Visual Studio Code issue, there are some suggested Visual Studio Code configuration changes that may help you to resolve this issue.
