### ISSUE TITLE
Not all local branches are visible on graph if they are far apart

### ISSUE THREAD

**Issue by mehlian** [mhutchie/vscode-git-graph#571] opened 2021-09-28 07:15 UTC
**Describe the Bug**
I am not sure if it is a bug or the repository is set up incorrectly, but I am not able to display all local branches on the chart.
I am also using Sourcetree where this problem does not occur.

As already mentioned, I have two local branches:
- main
- dev

The 'dev' branch only exists locally and the last commit is dated May 6, 2021. The 'main' branch, on the other hand, is constantly updated and reflects the status on the remote branch, which is also called 'main'. 

When in the graph view I select the 'show all local branches' option and start scrolling down the list to find this older branch - 'dev', after some time the commit list will stop refreshing and I am not able to get to the commit I am looking for.

![Screen Shot 28-09-21 at 08 51 01](https://user-images.githubusercontent.com/31826615/135037963-2fed4355-1dc8-4b94-b96e-304c2c5f62cf.png)

![Screen Shot 28-09-21 at 08 52 07](https://user-images.githubusercontent.com/31826615/135038027-60eabb57-c964-4661-8264-08ba4d023995.png)

When I select the option 'show me only the local dev branch', I see a view as if 'dev' was independent of the branch 'main'.

![Screen Shot 28-09-21 at 08 53 16](https://user-images.githubusercontent.com/31826615/135038413-3ef8f05c-d396-4143-b7df-c7684701f070.png)

For comparison, view of the repository in Sourcetree:

![Screen Shot 28-09-21 at 08 54 40](https://user-images.githubusercontent.com/31826615/135038607-fd8e9b43-e0fd-4fdb-be99-5cd2ab0fb574.png)

**Expected Behaviour**
By scrolling down, I will finally reach the local 'dev' branch.

**Environment**
 - Git Graph Extension Version: 1.30.0
 - Visual Studio Code Version: 1.60.2
 - Operating System: Windows 10

**Additional Context (optional)**
The inability to display both branches makes it difficult to merge the branches together.

**Comment by mhutchie** [comment] 2021-09-28 08:32
Hi @mehlian,

If you're working in a repository where you want to see a large number of commits (due to the separation of the branches), I'd recommend adjusting the [`git-graph.repository.commits.initialLoad`](https://docs.mhutchie.com/vscode-git-graph/general/extension-settings#commits-initial-load) to load more commits when the Git Graph View is first loaded. This will reduce or eliminate the need for additional commits to be loaded (either automatically by scrolling or pressing the "Load More Commits" button).

If you increase the value of this setting to be more than the number of commits required to reach the `dev` branch, can you confirm or deny whether the `dev` branch is visible?

The mechanism to determine whether more commits are available is extremely simple and robust, and has been unchanged since the extension was first released 2.5 years ago. If there was a fundamental issue with how it was being done, I'm sure at least one of the other ~1.7 million users would have reported it in this time (no one has). This leads me to think it's an isolated issue with your environment / repository / Git Graph settings, although it does seem suspicious considering SourceTree is displaying the commits as expected.

Would you please provide the Git information from the Git Graph Output Channel?
![image](https://user-images.githubusercontent.com/5315753/135052328-1a35ab5f-3685-43a8-a9af-2be4ab7d106e.png)

**Comment by mehlian** [comment] 2021-09-28 09:14
@mhutchie 
Increasing the number of visible commits using the 'git-graph.repository.commits.initialLoad' option did not help. The last commit is the same as when using auto-load feature (all commits are visible from start).

Output from 'Git Graph':
```
[2021-09-28 10:59:57.770] Starting Git Graph ...
[2021-09-28 10:59:58.099] Using C:\Program Files\Git\cmd\git.exe (version: 2.14.1.windows.1)
[2021-09-28 10:59:58.103] > git rev-parse --show-toplevel
[2021-09-28 10:59:58.103] Showing "Git Graph" Status Bar Item
[2021-09-28 10:59:58.103] Started Git Graph - Ready to use!
[2021-09-28 10:59:58.137] Successfully set Visual Studio Code Context "git-graph:codiconsSupported" to "true"
[2021-09-28 10:59:58.481] Searching workspace for new repos ...
[2021-09-28 10:59:58.481] Completed searching workspace for new repos
[2021-09-28 11:00:00.653] Created Git Graph View
[2021-09-28 11:00:00.939] > git branch -a --no-color
[2021-09-28 11:00:00.941] > git remote
[2021-09-28 11:00:00.943] > git reflog --format=... refs/stash --
[2021-09-28 11:00:01.004] Started watching repo: d:/**<path to project directory>**
[2021-09-28 11:00:01.012] > git -c log.showSignature=false log --max-count=10001 --format=... --date-order --branches --tags --remotes HEAD --
[2021-09-28 11:00:01.013] > git show-ref -d --head
[2021-09-28 11:00:01.407] > git status --untracked-files=all --porcelain
[2021-09-28 11:00:01.869] > git --no-pager config --list -z --includes
[2021-09-28 11:00:01.871] > git --no-pager config --list -z --includes --local
[2021-09-28 11:00:01.873] > git --no-pager config --list -z --includes --global
```

**Comment by mhutchie** [comment] 2021-09-28 09:25
@mehlian,

Thanks for providing that information. That test rules out an issue with the auto-load / load more commits functionality, as the last commit is the same.

Please run the Git command `git -c log.showSignature=false --no-pager log --max-count=10001 --oneline --date-order --branches --tags --remotes HEAD --` in a terminal. It will output a list of commits in the same order as the commits displayed in the Git Graph View. Is the last commit it returns the same as the last commit in the Git Graph View?

**Comment by mehlian** [comment] 2021-09-28 09:53
@mhutchie 
> Is the last commit it returns the same as the last commit in the Git Graph View?

No. The last commit in terminal is the first commit for this repo - 'initial commit'.

When I switch to the 'dev' branch and scroll to the very bottom, I can see that the last commit coincides with the one from the terminal. 

Based on this image:
https://user-images.githubusercontent.com/31826615/135038027-60eabb57-c964-4661-8264-08ba4d023995.png
where local 'main' branch is selected, it looks like maybe there is a limit to max number of commits that can be shown?

**Comment by mhutchie** [comment] 2021-09-28 10:31
@mehlian

There is definitely no maximum limit to the number of commits. (many users work in extremely large repositories)

The only possible way for this to be a bug in the extension is if Git Graph is unable to parse the output of the underlying Git command used to fetch the commit data. If a parsing error occurs, it will stop at the last commit that could successfully be parsed (i.e. the last commit you can see in the Git Graph View).

The easiest option would be for you to give me access to your repository so I can debug the issue, but I understand this may not be possible. If not, would you provide the output of `git -c log.showSignature=false --no-pager log --max-count=10001 --format="%H | %P | %aN | %an | %aE | %ae | %s" --date-order --branches --tags --remotes HEAD --`, but just for two commits (two consecutive lines in the Git output):
1. The line containing the data of the last commit displayed in the Git Graph View
2. The line directly after it in the output (which is the commit that may cause the parsing error).

If providing this Git output contains any sensitive information you don't want public, just replace any letters or numbers with "x"  (i.e. `a cat & dog - test` -> `x xxx & xxx - xxxx`). The key thing here is to preserve any non-alphanumeric characters, so I can debug the parsing code to try to replicate your issue. A regular expression to achieve this would be to replace `[A-Za-z0-9]` with `x`.

**Comment by mehlian** [comment] 2021-09-28 11:00
@mhutchie 
last commit visible in Git Graph:
>abeb7ed8891ed7e80bdc06f09d4562dc43c77697 | 912f9c10c73846a2735d6ea8d36a87837316cfb7 | xxxxxxxxxxx | xxxxxxxxxxx | xxxxxx.xxxxx@xxxxxxxxxxx.xx | xxxxxx.xxxxx@xxxxxxxxxxx.xx | xxx xxx [xxxxxx] - [xxxxxxxx] xx xxx xxxx xxxxxxxxx xx xxxxxxx xxx xxxx.
xxxxxxxxxxx - xxxxxxxxx xxxxxxxx xx xx xxxxxx xxxx xx xxxxx xxxxxxx

next commit
>647935671aa794cd642e69c3ba80523377758656 | e2e97ba75b93d3c3f7608b7ef0614f751e15c53f | xxxxxx xxxxxxxx | xxxxxx xxxxxxxx | xxxxxxxxxxx@xxxxxx.xxx | xxxxxxxxxxx@xxxxxx.xxx | xxx xxx [xxxxxx] - [xxxxxxxx] xxxx xxx xx xxxxx. xxxxx xxx xx "xxxxxxxxx xxxxxx", "xxxxxxx xxxxx" xxx.;

**Comment by mhutchie** [comment] 2021-09-28 11:24
@mehlian,

The format string I provided can be translated from `%H | %P | %aN | %an | %aE | %ae | %s` to:
* `%H` = Commit Hash
* `%P` = Parent Hash(es)
* `%aN` = Author Name (respecting mail map)
* `%an` = Raw Author Name
* `%aE` = Author Email (respecting mail map)
* `%ae` = Raw Author Email
* `%s` = Commit Subject

> last commit visible in Git Graph:
> > 
> > abeb7ed8891ed7e80bdc06f09d4562dc43c77697 | 912f9c10c73846a2735d6ea8d36a87837316cfb7 | xxxxxxxxxxx | xxxxxxxxxxx | xxxxxx.xxxxx@xxxxxxxxxxx.xx | xxxxxx.xxxxx@xxxxxxxxxxx.xx | xxx xxx [xxxxxx] - [xxxxxxxx] xx xxx xxxx xxxxxxxxx xx xxxxxxx xxx xxxx.
> > xxxxxxxxxxx - xxxxxxxxx xxxxxxxx xx xx xxxxxx xxxx xx xxxxx xxxxxxx

Was the subject (after the last `|`) split across two lines? The Git format argument `%s` (i.e. the commit subject) shouldn't contain new line characters as Git should be removing them. If it does contain a new line character, then that would definitely cause the parsing to fail, as it's expected that each commit is on a single line. If so, please let me know what character is causing the subject to be split onto multiple lines.

If possible, can you also try updating Git to a later version (to rule out a bug in your specific version of Git).

**Comment by mehlian** [comment] 2021-09-28 11:38
@mhutchie 
>Was the subject (after the last |) split across two lines?

Yes, its 'CR''LF' (0xD 0xA).

>can you also try updating Git to a later version

I would like to skip this step.

**Comment by mhutchie** [comment] 2021-09-28 12:24
> Yes, its 'CR''LF' (0xD 0xA).

I think the Git output / terminal is doing some conversion making it hard to see what the underlying root cause is, because this is just not possible according to the Git implementation (I've reviewed Git's source code to be sure).

---

Based on the information provided, there does appear to be some character in the subject of commit `abeb7ed8` that is causing the Git output of the commit to be split onto multiple lines. This is preventing Git Graph from being able to proceed with parsing subsequent commits in the Git output.

After reviewing the Git implementation to confirm my understanding of `%s` is sound, and because no other users have ever reported this issue occurring in their commits, I'm almost certain that the parsing method I've written should be fine (and doesn't contain a fundamental flaw). I think most likely there is some special character in the subject of commit `abeb7ed8` causing this to occur, however without a way to replicate the issue myself, I'm not able to implement a fix for it.

I'll close this issue for now as I'm unable to replicate it. However, if you or another user in the future are able to construct a simple repository that allows me to consistently replicate the issue, I'd happily re-open and implement a fix for it.

I'll also keep thinking about this to see if I can implement an alternative parsing method that is more resilient to special characters. However, frankly there are many other features for me to implement that add far more net value to all users (making it hard to justify spending significant time to attempt to fix an issue that I can't replicate and currently only affects one user in one repository for one commit).

**Closed as completed by mhutchie** 2021-09-28 12:24 UTC
Labels: bug, backlog

**Comment by mehlian** [comment] 2021-09-28 12:30
Thanks for your time.
Since I already know where the cause of this problem may be, when I find time, I will try to reproduce the problem on a test repo.

**Comment by mehlian** [comment] 2021-09-29 17:37
@mhutchie 
Here's the link to repository with corrupted message:
https://github.com/mehlian/test/tree/dev

Run this command in terminal after checking 'dev' branch to see all commits including last one that contains invalid character
`git log`
