### ISSUE TITLE
Strange mess in the title bar

### ISSUE THREAD

**Issue by kanlukasz** [mhutchie/vscode-git-graph#300] opened 2020-04-24 09:11 UTC
**Describe the Bug**
With the Git Graph window open and the terminal maximizing, you can see strange mess in title bar

**Steps to Reproduce**
### Video GIF:
![git](https://user-images.githubusercontent.com/30685349/80195429-1a7fa280-861c-11ea-8fba-d9f6f830e897.gif)

### Screen:
![obraz](https://user-images.githubusercontent.com/30685349/80195467-28352800-861c-11ea-8295-b34c4837c942.png)

**Environment**
 - Git Graph Extension Version: **latest**

```
Version: 1.44.2 (system setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
 - Operating System: *Windows 10*

**Comment by mhutchie** [comment] 2020-04-24 09:16
Closing as this is a duplicate of #234 & #247.

The extension uses a [Webview](https://code.visualstudio.com/api/extension-guides/webview) in Visual Studio Code for the main Git Graph View. The behaviour you're observing is to do with the incorrect positioning of the Webview over the Visual Studio Code Header, and occurs for any Webview from any extension. Visual Studio Code manages the positioning and lifecycle of Webviews, while extensions only contribute the content within it.

As this is a Visual Studio Code bug, **please raise it as a bug in the [vscode](https://github.com/Microsoft/vscode) repo**, so Microsoft can fix it. Since they upgraded to Electron 6.x in VSCode 1.40.0, there have been numerous frustrating bugs to do with their handling of Webviews, affecting all extensions that use Webviews.

I'm closing this bug as it is caused by, and needs to be fixed in Visual Studio Code, and there is nothing I can do within the extension to fix it in the interim.

**Closed by mhutchie** 2020-04-24 09:16 UTC
Labels: bug
